### ISSUE TITLE
macOS native framework header encoding breaks upload

### ISSUE THREAD

**Issue by tycho** [getsentry/sentry-cli#2130] opened 2024-08-26 19:00 UTC
### CLI Version

2.33.1

### Operating System and Architecture

- [x] macOS (arm64)
- [x] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

15.0 Beta (24A5320a), Xcode 16.0 beta 6 (16A5230g)

### CLI Command

```
sentry-cli upload-dif --org <org> --project <project> --include-sources --wait -- <binaries>
```

### Exact Reproduction Steps

1. Build a macOS app that uses some of the native macOS frameworks, e.g. IOKit.
2. Attempt to upload the symbols.

### Expected Results

Upload should succeed.

### Actual Results

Upload fails because many of the macOS framework headers haven't been touched for years and are not UTF-8 encoded:

```
  DEBUG   2024-08-26 11:52:46.111894 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDUsageTables.h
error: file could not be read as UTF-8
  caused by: stream did not contain valid UTF-8
```

### Logs

```
  DEBUG   2024-08-26 11:52:44.880200 -07:00 sentry-cli version: 2.33.1, platform: "darwin", architecture: "arm64"
  INFO    2024-08-26 11:52:44.881764 -07:00 sentry-cli was invoked with the following command line: "sentry-cli" "upload-dif" "--org" "introversion" "--project" "darwinia" "--include-sources" "--wait" "--" "ship/Darwinia-macOS-steam-2.3.3-295-g0dc3ac90b"
  INFO    2024-08-26 11:52:44.881803 -07:00 Issuing a command for Organization: introversion Project: darwinia
  DEBUG   2024-08-26 11:52:44.883057 -07:00 request GET https://sentry.uplinklabs.net/api/0/organizations/introversion/chunk-upload/
  DEBUG   2024-08-26 11:52:44.883073 -07:00 using token authentication
  DEBUG   2024-08-26 11:52:44.883223 -07:00 retry number 0, max retries: 0
  DEBUG   2024-08-26 11:52:44.899859 -07:00 > GET /api/0/organizations/introversion/chunk-upload/ HTTP/1.1
[...]
  DEBUG   2024-08-26 11:52:46.108774 -07:00 Trying to add source file: /Users/steven/Development/darwinia/contrib/SDL/src/hidapi/mac/hid.c
  DEBUG   2024-08-26 11:52:46.109416 -07:00 Trying to add source file: /Users/steven/Development/darwinia/contrib/SDL/src/hidapi/SDL_hidapi.c
  DEBUG   2024-08-26 11:52:46.110382 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDManager.h
  DEBUG   2024-08-26 11:52:46.110807 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDBase.h
  DEBUG   2024-08-26 11:52:46.110999 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFRunLoop.h
  DEBUG   2024-08-26 11:52:46.111219 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDKeys.h
  DEBUG   2024-08-26 11:52:46.111636 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDDeviceTypes.h
  DEBUG   2024-08-26 11:52:46.111894 -07:00 Trying to add source file: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/IOKit.framework/Headers/hid/IOHIDUsageTables.h
error: file could not be read as UTF-8
  caused by: stream did not contain valid UTF-8
  INFO    2024-08-26 11:52:46.116496 -07:00 Running update nagger update check
  DEBUG   2024-08-26 11:52:46.116509 -07:00 request GET https://release-registry.services.sentry.io/apps/sentry-cli/latest
  DEBUG   2024-08-26 11:52:46.116513 -07:00 retry number 0, max retries: 0
[...]
```

Tried posting a full log, but it complained it was larger than 65536 characters. Most of it is not really relevant to the problem at hand anyway.

**Comment by tycho** [comment] 2024-08-26 19:59
Currently working around this by using sentry-cli v2.32.0 on macOS systems.

**Comment by szokeasaurusrex** [comment] 2024-08-27 14:09
I am going to close this as a duplicate of #2124. This issue is directly caused by a problem in the upstream `symbolic` library (https://github.com/getsentry/symbolic/issues/860). We are working on a fix.

**Closed by szokeasaurusrex** 2024-08-27 14:09 UTC
Labels: Waiting for: Product Owner
