### ISSUE TITLE
Supports NVM in sentry-cli.js when build from XCode (React Native) - node no such file or directory

### ISSUE THREAD

**Issue by duyleekun** [getsentry/sentry-cli#421] opened 2018-10-31 07:39 UTC
Dependencies

```json
{
    "@babel/runtime": "^7.1.2",
    "add": "^2.0.6",
    "axios": "^0.18.0",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "lodash": "^4.17.10",
    "mobx": "^4.3.1",
    "mobx-react": "^5.1.0",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "numeral": "^2.0.6",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.1",
    "react-native-contacts": "^2.2.4",
    "react-native-fast-image": "^5.0.11",
    "react-native-firebase": "^5.0.0",
    "react-native-image-crop-picker": "^0.21.2",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-sentry": "^0.39.1",
    "react-navigation": "^2.12.1",
    "schedule": "0.4.0"
}
```

Currently, the sentry wizard made following change to `ProjectName.xcodeproj/project.pbxproj`

```diff
- shellScript = "export NODE_BINARY=node\n../node_modules/react-native/scripts/react-native-xcode.sh";
+ shellScript = "export SENTRY_PROPERTIES=sentry.properties\nexport NODE_BINARY=node\n../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh\n";
```

This breaks RN apps with RVM with following error
<img width="248" alt="image" src="https://user-images.githubusercontent.com/1965712/47772792-65b44000-dd1a-11e8-981f-c63486f739a6.png">

The reason is `scripts/react-native-xcode.sh` can leverage `nvm` node executable in [their script](https://github.com/facebook/react-native/blob/v0.57.4/scripts/react-native-xcode.sh#L46) but the `sentry-cli` script didn't

The fix was to copy the NVM handling part inside `scripts/react-native-xcode.sh` to build script to fix the above error.

**Comment by export-mike** [comment] 2018-11-11 19:30
looks related: https://github.com/getsentry/react-native-sentry/issues/484

commits: https://github.com/facebook/react-native/commit/ce25c54284c55248f5e6e340cc64711a130b660b

**Comment by export-mike** [comment] 2018-11-11 19:55
Looks like this is still a temporary solution that works: 
https://github.com/getsentry/react-native-sentry/issues/247

run this in your terminal - no edits required to project.pbxproj
```sh 
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
```

**Comment by ManAnRuck** [comment] 2019-12-28 07:21
https://docs.sentry.io/platforms/react-native/manual-setup/#using-node-with-nvm-or-notion
this works for me locally, but on travis-ci.com it does not work. (I use nvm on travis)
also the workaround https://github.com/getsentry/sentry-cli/issues/421#issuecomment-437699488 doesn't work for me on travis

**Comment by kamilogorek** [comment] 2020-03-05 13:54
@ManAnRuck what's the exact problem on CI you're running into?

**Comment by twelve17** [comment] 2020-06-19 18:34
It appears that the "no such file or directory" error is coming from the sentry-cli script, as it is a javascript script, and also runs with node:

```
$ head ./node_modules/@sentry/cli/bin/sentry-cli 
#!/usr/bin/env node
/* eslint-disable no-console */
```

The error is actually coming from `/usr/bin/env`, hence why the error message starts with "env:", because "/usr/bin/env" is not finding "node".

To confirm this, I changed this line of the build phase script :

```
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
```

To 

```
../node_modules/@sentry/cli/bin/sentry-cli -h
```

Which should just print the help page of the command. I still see the error:
```
env: node: No such file or directory
```

So the problem is that the script cannot find our `nvm`'s `node`.  

Why?

This is because xcode's build phase scripts run with an isolated environment.  XCode will create a wrapper shell script for each build phase script and run it with a preset environment. 

To see the the wrapper script, go to XCode's report navigator after the build fails:

![xcode-report-navigator-1](https://user-images.githubusercontent.com/788325/85166477-4192d300-b25f-11ea-8091-06f53fcb1fb2.png)

There are two notable things about this output. First, the `PATH` is missing the path to the `nvm`'s  `node`:

![xcode-report-navigator-2](https://user-images.githubusercontent.com/788325/85166951-f9c07b80-b25f-11ea-9e49-68dafa59a903.png)

Why? The answer is towards the end of the output:


![xcode-report-navigator-3](https://user-images.githubusercontent.com/788325/85166995-08a72e00-b260-11ea-8a89-155e0a6d1cd1.png)

After setting up a bunch of variables via `export ...`, xcode runs the temporary script via `sh -c`:

```
/bin/sh -c /Users/..../Script-030D431E0DE5414187450AD2.sh
```

The shell that runs the script is ran in non-interactive mode, which typically means it won't read the "profile" files, including the call to initialize nvm.  

I don't know if this is the best solution, but one way to fix this is to tell the build phase about nvm, and then to set the nvm version to use:

```
# this could be different for you
export NVM_DIR=$HOME/.nvm

if [ -n "$NVM_DIR" ]; then
  echo "nvm detected"
  source /usr/local/opt/nvm/nvm.sh
  # you might not need this, but we have different node versions on different
  # projects, and each project has an .nvmrc in its root directory. 
  # If it is present, set the node version corresponding to this project
  if [ -f "../.nvmrc" ]; then
    NODE_VERSION=$(cat ../.nvmrc)
    echo "nvmrc found at project root, using node version: ${NODE_VERSION}"
    nvm use ${NODE_VERSION}
  fi
  export NODE_BINARY=$(nvm which node)
else
  export NODE_BINARY=node
fi
```

**Comment by twelve17** [comment] 2020-07-16 13:46
@export-mike  would you be open to a PR to add nvm support to the sentry build phases? It would probably require a similar approach to what the react native team did, and would need to be wrapped in a shell script.

**Comment by export-mike** [comment] 2020-09-09 03:00
Not really I don't think this is an issue for me anymore. @twelve17  this was 2 years ago

**Comment by twelve17** [comment] 2020-09-17 18:27
@export-mike  This indeed is an old issue, but it is still reproducible.  Are you sure it's not an issue because you've done the workaround of symlinking node to /usr/local?

**Comment by zkrige** [comment] 2020-10-23 11:17
This is indeed still an issue

**Comment by airtonix** [comment] 2021-04-27 09:02
really.. i can not fathom why the react-native team opt'd to be o proscriptive about the node version manager tooling .

simply could of instead `source $REPOROOT/.react-native-env.sh` where we put our own choice of node version manager...

**Comment by twelve17** [comment] 2021-05-14 23:29
> really.. i can not fathom why the react-native team opt'd to be o proscriptive about the node version manager tooling 

Is it really proscriptive? From the time the script was revived, it looked not just for `nvm` but also for `nodenv`:

https://github.com/facebook/react-native/commit/b8c86b8deced01027b609959576ffcf5d2d0f520#diff-0eeea47fa4bace26fa6c492a03fa0ea3923a2d8d54b7894f7760cb9131ab65ebR64

It doesn't seem like the script is  _only_ allowing node to be ran from those version managers.

> where we put our own choice of node version

That would be a super nice solution for this project!

On Facebook's side, I can see how adding a few popular options out of the box might save some headaches internally and externally.

**Comment by nickyleach** [comment] 2021-06-03 18:30
Inspired by @twelve17 and the [find-node.sh](https://github.com/facebook/react-native/blob/502b81904998b800f2d960bb4a8e244988c72958/scripts/find-node.sh) script in React Native, I created a wrapper script for `node` that lives under `/usr/local/bin/node`:

```bash
#!/usr/bin/env bash

# I don't expect this file to get used often! nvm has been added to the path
# and in most cases will be accessed directly. I'm just adding this file
# because the React Native Sentry package doesn't seem to handle nvm very
# well. It expects /usr/local/bin/node to be a valid executable and I want
# to make sure that executable handles .nvmrc files.
#
# https://github.com/getsentry/sentry-cli/issues/421

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  . "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi

nvm use

exec node "$@"
```

**Comment by Natteke** [comment] 2021-06-08 14:36
2021, still an issue

**Comment by duyleekun** [comment] 2021-07-03 09:07
Because of this issue, I chose to ditch the NVM in CI environment 2 years ago. I just stick to normal node installation since it's the most natural way to use node anyway. Haven't looked back since.

**Comment by twelve17** [comment] 2021-07-03 11:43
Technically you have looked back if you’re here again ;)

**Comment by kamilogorek** [comment] 2021-10-15 12:48
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Closed by kamilogorek** 2021-10-15 12:48 UTC
Labels: enhancement, need more information, component: react-native

**Comment by fqf** [comment] 2021-10-20 03:10
> Looks like this is still a temporary solution that works: [getsentry/sentry-react-native#247](https://github.com/getsentry/sentry-react-native/issues/247)
> 
> run this in your terminal - no edits required to project.pbxproj
> 
> ```shell
> n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
> ```

thanks man!

**Comment by tobiastornros** [comment] 2022-02-01 15:59
Reporting from 2022. Still an issue

**Comment by airtonix** [comment] 2022-02-03 20:36
We're just going to move to using ASDF as it's the superior choice to any other specific language engine manager and is based on shims so not affected by problems that nvm has.

**Comment by Norcy** [comment] 2023-07-13 13:07
> Looks like this is still a temporary solution that works: [getsentry/sentry-react-native#247](https://github.com/getsentry/sentry-react-native/issues/247)
> 
> run this in your terminal - no edits required to project.pbxproj
> 
> ```shell
> n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
> ```

Thanks for saving my time.

For me, it can simplify to this 

```sh
n=$(which node);sudo cp -r $n /usr/local
```
