### ISSUE TITLE
Error uploading sourcemaps after upgrade to 1.19.0

### ISSUE THREAD

**Issue by andrew-me** [getsentry/sentry-cli#113] opened 2017-08-17 14:50 UTC
We're using the cli to upload source maps.
All has been working for a while. Since auto updating to 1.19.0 we get the following error:

`error: Is a directory (os error 21)
Exited with code 1`

Here's our code:

```
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -sL https://sentry.io/get-cli/ | bash
              sentry-cli releases new ${CIRCLE_SHA1}
              sentry-cli releases files ${CIRCLE_SHA1} upload-sourcemaps dist/
              rm -rf dist/**/*.map
            fi
```

Screenshot:

![image](https://user-images.githubusercontent.com/2700262/29418266-c87c58ce-8363-11e7-933b-dafc9a673ab1.png)

Any ideas what might be causing our issue?

**Comment by andrew-me** [comment] 2017-08-17 15:21
We rolled back to 1.18.0 using installation via npm: https://docs.sentry.io/learn/cli/installation/#installation-via-npm

**Comment by ianformanek** [comment] 2017-08-17 15:45
We just started hitting the same issue, also rolled back to 1.18.0.
Thanks @andrew-me for filing the issue and the quick downgrade description!

**Comment by rjz** [comment] 2017-08-17 17:07
Same issue here on Circle CI (Ubuntu 14.04) with sentry-cli 1.19.0.

**Comment by mitsuhiko** [comment] 2017-08-17 20:00
Duplicate of #112

**Closed by mitsuhiko** 2017-08-17 20:00 UTC
