### ISSUE TITLE
Structured output feature

### ISSUE THREAD

**Issue by seanhoughtonatvi** [getsentry/sentry-cli#2128] opened 2024-08-25 23:21 UTC
The output of the CLI is in human-readable tabular format. I looked through the code and the docs and it appears that there is no way to get csv, json, yaml, or any other structured output. This makes using the CLI as part of a script much more challenging.

I would like to be able to provide an `--output-format=json` argument and get tabular data formatted as a json list of objects.

**Comment by szokeasaurusrex** [comment] 2024-08-26 07:56
Hi @seanhoughtonatvi, thank you for the suggestion. For which specific command(s) are you requesting this feature?

**Comment by seanhoughtonatvi** [comment] 2024-08-26 15:57
I was looking in to using sentry-cli to create a weekly summary report that includes a list of unresolved issues rather than numerical totals like [the built-in summary](https://docs.sentry.io/product/alerts/notifications/#weekly-reports). This would use `sentry-cli issues list --project xxxx`.

Any command that uses https://github.com/getsentry/sentry-cli/blob/master/src/utils/formatting.rs#L27 would probably benefit from structured output so it can be piped into tools like `jq`.

I've since realized that there's no command to actually retrieve information about a specific issue (!) - so it looks like this tool isn't really intended as a general-purpose CRUD interface to Sentry. I'm going to change my approach and generate an SDK with swagger-codegen and write an application that uses the REST interface rather than a script. The CLI would have made a prototype easier.

**Comment by szokeasaurusrex** [comment] 2024-08-27 14:03
Ah understood. Yeah, the `sentry-cli` only performs a subset of the actions available from the [Sentry web API](https://docs.sentry.io/api/). 

If the structured output feature cannot help you anyways with what you are trying to accomplish, I will just leave the issue open on our backlog with low priority. If more folks request this feature, we can increase the priority.

If having the ability to query information about a single issue in the CLI would be helpful for you, you can feel free to open another feature request

**Comment by szokeasaurusrex** [comment] 2024-10-09 12:47
Structured output would also be helpful for the JavaScript bundler plugins

**Comment by szokeasaurusrex** [comment] 2024-12-10 11:42
Duplicate of #1416

**Closed by szokeasaurusrex** 2024-12-10 11:42 UTC
