### ISSUE TITLE
"sentry-cli - error: Failed to load .sentryclirc file from project path"

### ISSUE THREAD

**Issue by poitch** [getsentry/sentry-cli#1946] opened 2024-02-16 22:07 UTC
### Environment

`$ sentry-cli --version
sentry-cli 2.28.6`

MacOS 14.1
XCode 15.2 (15C500b)

### Steps to Reproduce

`brew install getsentry/tools/sentry-wizard && sentry-wizard -i ios`
in my project directory

Then Command + B in my project to build, I get a warning during the build phase that sentry-cli cannot find the .sentrylirc file. I have verified that the file exists and has the proper permissions set.

### Expected Result

No warning during the build phase and symbols uploaded

### Actual Result

Symbols aren't uploaded.

### Logs

Unfortunately adding --log-level or exporting the env. variable do not produce any output. Even after removing > /dev/null in the build phase that was added.

**Comment by szokeasaurusrex** [comment] 2024-02-19 09:00
Closing, because this issue is most likely a duplicate of #1902. 

This issue occurs because Xcode runs build scripts in a sandbox. You need to add the `.sentryclirc` file to the list of input files, which you can do by following [these instructions](https://github.com/getsentry/sentry-cli/issues/1902#issuecomment-1906088229). 

If you are still experiencing this problem after following the instructions linked above, please reopen the issue, and I would be happy to help you :)

**Closed by szokeasaurusrex** 2024-02-19 09:00 UTC
Labels: Waiting for: Product Owner
