### ISSUE TITLE
how to increase the performance of sentry-cli sourcemaps inject ?

### ISSUE THREAD

**Issue by mtariqsajid** [getsentry/sentry-cli#1713] opened 2023-08-08 11:03 UTC
first sentry try to build sourcemap then it upload to sentry server the issue  is the build take too much time and cpu 25% use only how to improve the speed of this process and use the cpu 100%.

is sentry cli @sentry/cli build on rust ?
i am uploading throw my computer not from CI/CD so i have a lot of cpu power (16 core )

**Comment by kamilogorek** [comment] 2023-08-08 13:26
Duplicate of https://github.com/getsentry/sentry-cli/issues/1710 Will close this one to track the issue in one place.

**Closed by kamilogorek** 2023-08-08 13:26 UTC
