### ISSUE TITLE
App Center Support

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-cli#263] opened 2018-03-02 04:05 UTC
I saw in this file that `code-push` is being used:

https://github.com/getsentry/sentry-cli/blob/947ed13fedda3d1e5e7409647667f7fa9016e20b/src/utils/codepush.rs#L27

Based on the following graphic, that command will not work in "late March 2018":

http://microsoft.github.io/code-push/assets/ga/timeline.png

Are there plans to use `appcenter` going forward?  I am using `appcenter` for everything else CodePush related.  I think with the linked code above being as it is, I will likely have to also use `code-push` just to upload assets to Sentry.

**Comment by mitsuhiko** [comment] 2018-03-03 12:34
Duplicate of #218

**Closed by mitsuhiko** 2018-03-03 12:34 UTC
