### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cli#86] opened 2017-06-20 23:33 UTC
sentry-cli 1.13.3

full debug output:
[sentry-cli-413-output.txt](https://github.com/getsentry/sentry-cli/files/1089927/sentry-cli-413-output.txt)

If I run the command a second time, I get a "nothing to compress"/"nothing to upload" but the last time I did a release and this happened, all of my stacktraces for that particular release were not symbolicated ([example](https://sentry.io/recharge/consumer-ios/issues/245126383/))

**Comment by mitsuhiko** [comment] 2017-06-20 23:52
Thanks for reporting. We're going to investigate this.

**Comment by edenman** [comment] 2017-06-22 22:52
Any luck?  I'm about to roll another beta of my app and I'd really like to get symbolicated crash reports when I upload it to the app store

**Comment by mattrobenolt** [comment] 2017-06-22 22:53
Does this fail 100% of the time for you? Or does it work some of the time? I haven't spent a ton of time investigating this yet, other than nothing appears to obviously be messed up on our side and I haven't personally been able to reproduce.

**Comment by edenman** [comment] 2017-06-22 22:55
100% failure rate on the last few (three or four?) releases I've built.  Obviously I can't test the same build twice bc the second time I run the command, it says there's nothing to upload :/

**Comment by mitsuhiko** [comment] 2017-06-22 23:13
@edenman still looking but what's odd is that it says that the files are up. Because we only upload files missing on the server so the server considers them to be there. Mysterious.

**Comment by edenman** [comment] 2017-06-23 00:03
Would it be helpful to send you the raw files so you can upload them yourself and debug it live?

**Comment by mattrobenolt** [comment] 2017-06-23 00:04
@edenman If you can, feel free to email me directly. matt@. I'm literalyl unable to reproduce this, but I have some theories of how it can happen, but they're pretty contrived. I think it's a cascading failure.

**Comment by karlisl** [comment] 2017-06-28 13:02
Same thing is happening for us with sentry-cli version 1.16.0 and has been happening 90% of the time for quite some time now.

```
[05:42:03]: sentry-cli 1.16.0 installed!
[05:42:03]: Starting sentry-cli...
[05:43:11]: Batch 1
[05:43:11]: > Found 21 debug symbol files. Checking for missing symbols on server
[05:43:11]: > Compressing 21 missing debug symbol files
[05:43:11]: > Uploading debug symbol files
[05:43:11]: error: http error: generic error (413)
```

It was also happening with Sentry Fastlane plugin and we already reported it earlier: https://forum.sentry.io/t/cannot-upload-ios-dsym-file-error-413-entity-too-large/707/6
which resulted in issue https://github.com/getsentry/sentry-cli/issues/62.

**Comment by mitsuhiko** [comment] 2017-07-17 17:16
We changed the default in 1.17.0 to upload smaller archives. This won't fix the issue but should make it less common.

**Comment by mitsuhiko** [comment] 2017-11-20 11:34
Going to close this as there have not been any reports in a long time.

**Closed by mitsuhiko** 2017-11-20 11:34 UTC
Labels: bug

**Comment by karlisl** [comment] 2017-11-20 19:04
@mattrobenolt @mitsuhiko Thank you guys for looking into this, much appreciated!

**Comment by fcoury** [comment] 2017-12-07 15:57
My application has a large state and I am using the sentry redux middleware. I am running into this error. Is there a way around it?

**Comment by fcoury** [comment] 2017-12-07 15:57
To add to my previous message:

`Content-Length:183107` so around 183kb. Is that too large?

**Comment by mitsuhiko** [comment] 2017-12-07 18:49
@fcoury are you sure this is related to sourcemap uploading?

**Comment by fcoury** [comment] 2017-12-07 18:51
@mitsuhiko I am sure this is not related to that. Sorry! I think I chose the wrong issue to comment on.

**Comment by jan-auer** [comment] 2017-12-07 19:16
FWIW, looks like you're trying to submit an error event from the redux middleware and those are limited to somewhere around 100kb. You could try to trim down the payload and if that's not possible open an issue in repo of the respective integration that you're using.

**Comment by fcoury** [comment] 2017-12-07 20:15
Thanks @jan-auer I have done that and it seems to be working now.
