### ISSUE TITLE
can not upload sourcemap, please take a look.

### ISSUE THREAD

**Issue by xueqingxiao** [getsentry/sentry-cli#215] opened 2018-01-11 08:39 UTC
```log
error: http error: [55] Failed sending data to the peer (Send failure: Broken pipe)
```
I can stably reproduce this issue when file size is 1~2M. please take a look, thanks.

**Comment by jan-auer** [comment] 2018-01-11 09:22
Duplicate of #40. Please continue discussion in the other issue and post the **exact command and full output** with debug log level:

```
sentry-cli --log-level=debug upload-...
```

Important information would also be:
 - Are you using sentry.io (hosted), a self-hosted version, or local Sentry?
 - Are you running behind some sort of firewall?

**Closed by jan-auer** 2018-01-11 09:22 UTC
