### ISSUE TITLE
SENTRY_PROPERTIES has no effect

### ISSUE THREAD

**Issue by posidron** [getsentry/sentry-cli#531] opened 2019-05-19 07:37 UTC
**Sentry**: sentry-cli 1.43.0
**Node**: v12.0.0
**OS**: MacOS 10.14.4

I noticed there is already a bug filed [here](https://github.com/getsentry/sentry-cli/issues/458) but has 0 traction. Not sure why because it's seem really not to be working. ;-)

From https://docs.sentry.io/cli/configuration/#properties-files

```
export SENTRY_PROPERTIES=/tmp/sentry.properties
./node_modules/@sentry/cli/bin/sentry-cli info --log-level info
```

The output from `Loaded config from ...` does not match and it tries *always* to load the `.sentryclirc` from the project's root. 

The same of course applies when using `new SentryCli(<path>)` which parameter overwrites `process.env.SENTRY_PROPERTIES`.

**Comment by namutaka** [comment] 2019-05-26 05:33
I got a similar problem.
In my case, It seems sentry-cli loads  config parameters from a file specified SENTRY_PROPERTIES. But some parameters are not used when running `send-event` command.

I think `send-event` command uses only `SENTRY_DSN` environment variable or `auth.dsn` parameter in SENTRY_PROPERTIES file. (SENTRY_URL, SENTRY_AUTH_TOKEN, etc.. have no effect.)

In `send-event`, config.get_dsn() is used.
https://github.com/getsentry/sentry-cli/blob/master/src/commands/send_event.rs#L232

But get_dsn() doesn't use SENTRY_URL and SENTRY_AUTH_TOKEN and etc...
https://github.com/getsentry/sentry-cli/blob/1.44.1/src/config.rs#L339-L347

**Comment by kamilogorek** [comment] 2020-03-06 13:54
Duplicate of https://github.com/getsentry/sentry-cli/issues/458

**Closed by kamilogorek** 2020-03-06 13:54 UTC
