### ISSUE TITLE
Don't upload files one by one but compress into one file 

### ISSUE THREAD

**Issue by sheerun** [getsentry/sentry-cli#405] opened 2018-10-03 12:51 UTC
I think main reason of slow upload is uploading them one by one. With hundreds of files in my project the latency for each upload adds up and upload takes 5 minutes or longer.. Would it be possible for sentry-cli to upload just one file with all sources compressed inside?

**Comment by sheerun** [comment] 2018-10-03 13:09
Here, please experience my pain. 10 minutes of uploading sources :(

https://asciinema.org/a/JEdp9Lc7NTcxIBRTy47tTYLGm

**Comment by jan-auer** [comment] 2018-10-03 13:11
Duplicate of https://github.com/getsentry/sentry-cli/issues/309

We are aware that the source map upload is currently unbearably slow for some users and are already working on a fix. Please refer to the linked issue for updates. We will post comments there once we have a solution ready.

**Closed by jan-auer** 2018-10-03 13:11 UTC

**Comment by sheerun** [comment] 2018-10-03 13:28
Well, this is not duplicate of #309 as this one notes sourcemaps are not compressed when uploaded. I rather notice that they are also not archived and uploaded as one.  But it's OK if you want to join issues, I'll post it there.

**Comment by HazAT** [comment] 2018-10-03 13:30
@sheerun Can you try to add `--rewrite` to your sentry-cli command?

**Comment by sheerun** [comment] 2018-10-03 13:38
@HazAT With `--rewrite` upload takes 10-20% longer

**Comment by sheerun** [comment] 2018-10-03 13:41
In short it takes at least 1s for uploading one file, no matter the size

**Comment by sheerun** [comment] 2018-10-03 13:55
Not that making your api faster is a solution (the only solution is to make as few requests as possible), but here's a reason why each upload takes 1. Here are timings for my 21 Mbps (i.e. fast) connection in Poland for google.com:

```
curl -s -w '\nLookup time:\t%{time_namelookup}\nConnect time:\t%{time_connect}\nPreXfer time:\t%{time_pretransfer}\nStartXfer time:\t%{time_starttransfer}\n\nTotal time:\t%{time_total}\n' -o /dev/null https://google.com

Lookup time:	0.005308
Connect time:	0.019837
PreXfer time:	0.075593
StartXfer time:	0.113447

Total time:	0.113595
```

And here is for your API:

```
curl -s -w '\nLookup time:\t%{time_namelookup}\nConnect time:\t%{time_connect}\nPreXfer time:\t%{time_pretransfer}\nStartXfer time:\t%{time_starttransfer}\n\nTotal time:\t%{time_total}\n' -o /dev/null https://sentry.io/api/0/projects/

Lookup time:	0.013383
Connect time:	0.153392
PreXfer time:	0.443326
StartXfer time:	0.590191

Total time:	0.590362
```

So it takes just two requests for upload time to go above 1s.
