### ISSUE TITLE
sentry-cli throws 'error: http error: generic error (504)' on uploading dSYMs

### ISSUE THREAD

**Issue by pranjaltech** [getsentry/sentry-cli#89] opened 2017-06-27 11:10 UTC
Here's what I'm trying to do: 

```sh
$ sentry-cli --auth-token MY_AUTH_TOKEN upload-dsym --org MY_ORG --project MY_PROJECT ./AppName.app.dSYM.zip
Batch 1
> Found 30 debug symbol files. Checking for missing symbols on server
> Compressing 2 missing debug symbol files
> Uploading debug symbol files
error: http error: generic error (504)
```

I am using the latest version of sentry. 
```sh
$ sentry-cli --version
sentry-cli 1.16.0
```

**Comment by fjbelchi** [comment] 2017-07-07 16:52
Still happening? I have the same issue

**Comment by mitsuhiko** [comment] 2017-07-17 09:13
This most likely is a duplicate of #86.

**Closed by mitsuhiko** 2017-07-17 09:13 UTC
