### ISSUE TITLE
Source bundle creation fails on PE with embedded PPDB

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-cli#1491] opened 2023-02-24 01:42 UTC
Sentry CLI 2.13.0 added support for PPDB embedded in the PE assembly with #1463.  That's working fine, and will also use the embedded debug info to derive sources when using `sentry-cli dif upload --include-sources`.  However, I can't seem to use an embedded PPDB when trying to separately create a source bundle using `sentry-cli dif bundle-sources`.

In other words, this works:

```
dotnet new console -n ConsoleApp1
cd ConsoleApp1
dotnet build
sentry-cli dif bundle-sources obj/Debug/net7.0/ConsoleApp1.pdb
```

But this doesn't work, and it should:

```
dotnet new console -n ConsoleApp1
cd ConsoleApp1
dotnet build -p:DebugType=embedded
sentry-cli dif bundle-sources obj/Debug/net7.0/ConsoleApp1.dll
```

Even though this works:

```
dotnet new console -n ConsoleApp1
cd ConsoleApp1
dotnet build -p:DebugType=embedded
sentry-cli dif upload obj/Debug/net7.0/ConsoleApp1.dll --include-sources
```

**Comment by mattjohnsonpint** [comment] 2023-02-24 01:43
The output when failed is simply:
```
skipped obj/Debug/net7.0/ConsoleApp1.dll (no files found)
```

**Comment by vaind** [comment] 2023-02-27 12:58
The difference lies in `debug-files upload` executing `search_difs()->collect_object_dif()` which expands the given path to the actually useful file, i.e. `ConsoleApp1.pdb`. This is because upload-dif is normally used with a directory path, not individual file path.

`bundle-sources` doesn't do that, it just takes the single given file path and processes it.

Whether these two should behave like that - not sure. There are arguments both ways for each situation...

**Comment by szokeasaurusrex** [comment] 2024-12-11 11:12
Closing – per @vaind's [comment](https://github.com/getsentry/sentry-cli/issues/1491#issuecomment-1446280636), this appears to be expected behavior

**Closed by szokeasaurusrex** 2024-12-11 11:12 UTC
Labels: Status: Backlog
