### ISSUE TITLE
`sentry-cli releases deploy` breaks when release starts with "new"

### ISSUE THREAD

**Issue by chriscrowe** [getsentry/sentry-cli#785] opened 2020-07-09 20:58 UTC
Platform: Docker `alpine:3.12`
Sentry CLI: 1.55

It seems that when you have a release version that starts with the characters ‘new’, you're unable to mark it as deployed using the CLI. The release version gets misinterpreted as a command and produces an error like this:

```
sentry-cli releases deploys “${SENTRY_RELEASE}” new -e “${CI_COMMIT_BRANCH}” --log-level=${SENTRY_LOG_LEVEL}
 error: The subcommand ‘new-my-version’ wasn’t recognized
	Did you mean ‘new’?
```

Notably, creating the release works just fine. It only breaks when you try to mark it as deployed.

**Comment by kamilogorek** [comment] 2020-07-10 08:42
Duplicate of https://github.com/getsentry/sentry-cli/issues/785

**Closed by kamilogorek** 2020-07-10 08:42 UTC

**Comment by ahijaouy** [comment] 2020-07-10 12:51
> Duplicate of #785 (kinda, as it's same underlying issue).

@kamilogorek, I think you mistakenly marked this issue as a duplicate of itself...

**Comment by kamilogorek** [comment] 2020-07-10 13:08
Oh snap, thanks @ahijaouy!

Duplicate of https://github.com/getsentry/sentry-cli/issues/686
