### ISSUE TITLE
sentry-cli releases --clear not removing commits

### ISSUE THREAD

**Issue by christianbundy** [getsentry/sentry-cli#1019] opened 2021-09-06 17:41 UTC
### Environment

SaaS (https://sentry.io/)

### Version

1.68.0

### Steps to Reproduce

1. `sentry-cli releases set-commits "$VERSION" --clear`
2. See "Clearing commits for release" output
3. Go to release page for `$VERSION` on sentry.io

### Expected Result

Commits are no longer associated.

### Actual Result

Commits are still associated. Maybe the bug is caused by the ridiculous number of commits associated with this release? (Trying to enable 'suspect commits' and this single-commit release got thousands of commits accidentally associated.)

![image](https://user-images.githubusercontent.com/537700/132249797-be4121f5-638f-4485-a579-09684b93837f.png)

**Comment by kamilogorek** [comment] 2021-09-07 09:24
@getsentry/workflow I don't remember with whom exactly, but I had a conversation about this once.
The issue is that CLI is performing a correct request to the endpoint https://github.com/getsentry/sentry-cli/blob/master/src/api.rs#L777-L795
However, there is a minor difference between `refs` and `commits` which is kinda tangled up here _and_ in Sentry's codebase, making this feature misbehave.
ref: https://github.com/getsentry/sentry/blob/824f48f9e7a041afd9ded3b8d51bfbef4a15e9c2/src/sentry/api/endpoints/organization_releases.py#L469-L478

Could someone from the team elaborate on this one please?

**Comment by christianbundy** [comment] 2021-09-07 14:21
The real problem I'm trying to solve: I'm trying to backfill historical releases with commit metadata, and while the local command succeeds and tells me that it's associating commits... nothing shows up in the web UI. I thought maybe the UI was querying a replica with high latency, but it's been 24+ hours.

My hunch is that _maybe_ the problem is caused by a few releases that I have which somehow have thousands of commits associated. Maybe a commit can only be associated with 1 release at a time? So I've tried to clear all commits from all releases to workaround this potential problem, but then I'm bumping into this bug.

My script, FWIW:

```sh
#!/usr/bin/env bash

set -eou pipefail

 for commit_id in $(< commit-list); do
     git reset --hard $commit_id
     sentry-cli releases set-commits --clear $commit_id
done

for commit_id in $(< commit-list); do
    git reset --hard $commit_id
    sentry-cli releases set-commits --auto $commit_id --ignore-empty --ignore-missing
done

**Comment by christianbundy** [comment] 2021-09-11 15:43
Anything I can do to help move this forward?

I've had a ticket open with Sentry support and they've told me that I'll receive support via this GitHub issue instead (?).

If it helps, I've also used `curl` to replicate this problem, so I think you're right that the API is misbehaving and it's not just he CLI.

**Comment by NisanthanNanthakumar** [comment] 2021-09-14 22:17
hey @christianbundy I'm going to take a deeper look into this. Thanks for bringing it up!

**Comment by christianbundy** [comment] 2021-09-14 22:24
Cool, thank you!

**Comment by NisanthanNanthakumar** [comment] 2021-09-24 18:26
@christianbundy https://github.com/getsentry/sentry/pull/28831 This PR should fix the `clear` command.

**Comment by kamilogorek** [comment] 2021-09-27 12:08
Closing this one then, as it's not CLI issue. Thanks @NisanthanNanthakumar!

**Closed by kamilogorek** 2021-09-27 12:08 UTC

**Comment by christianbundy** [comment] 2021-09-27 16:20
Thank you! I'm excited to have this fixed.
