### ISSUE TITLE
Skip update check when running in CI

### ISSUE THREAD

**Issue by sandstrom** [getsentry/sentry-cli#1822] opened 2023-11-15 10:48 UTC
Maybe skip the update check when running in CI? (speed and bandwidth)

I know we can set `SENTRY_DISABLE_UPDATE_CHECK`, but just skipping it seems like a reasonable default.

https://github.com/getsentry/sentry-cli/blob/245eae22f203207b2707465f293eb1ce323f3518/src/config.rs#L539

Just a thought. Feel free to close this issue if you disagree.

**Comment by loewenheim** [comment] 2023-11-16 16:59
Hi, sorry for the late reply. I'm not sure how `sentry-cli` would detect that it's running in CI. Or do you mean that not checking for updates should be the default?

**Comment by sandstrom** [comment] 2023-11-16 17:04
@loewenheim It actually does already:

https://github.com/getsentry/sentry-cli/blob/9e967e32ce5a2c092514f73414e9ad9aac20048a/scripts/install.js#L52

`CI` is a common env variable that most CI servers will set.

**Comment by loewenheim** [comment] 2023-11-16 17:14
Interesting, I actually didn't know about this. I think this would make sense, yeah.

**Comment by szokeasaurusrex** [comment] 2023-12-12 15:20
I have placed the issue on our internal backlog, but since we have other higher priority issues to work on, it might take us some time before we get around to this issue. However, we accept contributor PRs, so if you would like to try to make this change yourself and submit a PR, we would be happy to review it!

**Comment by szokeasaurusrex** [comment] 2024-02-20 16:12
Hi @sandstrom, I believe we already are skipping the update check in CI, just we are performing the check elsewhere and we are doing it by checking whether the terminal session is attended. The line I believe is performing the check is located [here](https://github.com/getsentry/sentry-cli/blob/d40849a4dc51bb6e9a5c6312d335678be07e8de7/src/utils/update.rs#L267).

Therefore, I am going to close this issue for now. If you have ever experienced a situation where the update check was performed in CI despite this check, please reopen the issue and let me know how to reproduce what you saw.

**Closed by szokeasaurusrex** 2024-02-20 16:12 UTC
Labels: enhancement, help wanted, Status: Backlog

**Comment by sandstrom** [comment] 2024-02-20 18:55
@szokeasaurusrex Awesome, thanks!
