### ISSUE TITLE
Version detection changed since 2.8.0

### ISSUE THREAD

**Issue by Christophe31** [getsentry/sentry-cli#1372] opened 2022-10-25 10:20 UTC
### Environment

debian in gitlab cli. I use the docker latest (2.8.0)

### Steps to Reproduce

```
docker run --rm \
	-v $(PROJECT_DIR):/work \
	-e SENTRY_URL=https://sentry.project.net/ \
	-e SENTRY_ORG=org \
	-e SENTRY_PROJECT=project \
	-e SENTRY_AUTH_TOKEN \
	-e CI_ENVIRONMENT_NAME \
	-e CI_COMMIT_SHA \
	-e CI_ENVIRONMENT_NAME \
	-w /work \
	getsentry/sentry-cli \
	sentry-cli releases propose-version
```

### Expected Result

Get a version as the folder have  a .git folder.
It worked in previous releases

### Actual Result
```
error: Could not automatically determine release name
```

Note, I interpolated my results to avoid sending you the all bash script:
```bash
#!/usr/bin/env bash
export VERSION=$(sentry-cli releases propose-version)
sentry-cli releases new "$VERSION"
sentry-cli releases set-commits "$VERSION" --auto
```

**Comment by rafarbop** [comment] 2022-10-31 18:16
Hi
I pass for the same problem last week when the CI/CD of my project was try notify sentry of a new release
The command `sentry-cli releases propose-version` 
The retunn was "error: Cloud not automatically determine release name"
I try `sentry-cli info` and `export SENTRY_LOG_LEVEL=debug`, but a can't see anything the caused this problem

SOLVED - DOWNGRADED the Version:
I just changed the versioin of Sentry used in the project : 
`curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.7.0" bash`

And after that the command work fine, but a don't now how to fix the version 2.8.0

**Comment by kamilogorek** [comment] 2022-11-02 16:44
Duplicate of https://github.com/getsentry/sentry-cli/issues/1373
Please see the comment here https://github.com/getsentry/sentry-cli/issues/1373#issuecomment-1300873046

**Closed by kamilogorek** 2022-11-02 16:44 UTC

**Comment by Christophe31** [comment] 2022-11-04 09:49
Thank you, I confirm the user-group mapping fixed the issue.
