### ISSUE TITLE
the platform of getsentry/rust-musl-cross images on docker hub is amd64 regardless of tagged platform

### ISSUE THREAD

**Issue by koreno** [getsentry/sentry-cli#1405] opened 2022-11-29 15:54 UTC
![image](https://user-images.githubusercontent.com/180551/204577371-2f04623c-d6f0-4cd9-9ac6-b3d5f4be6e72.png)

### Steps to Reproduce

tried to `docker build -t .` on an aarch64 platform.

### Expected Result

successful build of docker image

### Actual Result

```
[centos@ip-172-31-3-238 sentry-cli]$ docker build --no-cache --platform linux/arm64/v8 --build-arg BUILD_ARCH=aarch64 -t sentry-cli .
Sending build context to Docker daemon  748.5kB
Step 1/18 : ARG BUILD_ARCH=aarch64
Step 2/18 : ARG BUILD_LIBC=musl
Step 3/18 : FROM getsentry/rust-musl-cross:$BUILD_ARCH-$BUILD_LIBC AS sentry-build
 ---> beec240083fe
Step 4/18 : ARG BUILD_ARCH
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 4a8624f7d08e
...
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by kamilogorek** [comment] 2022-11-29 16:46
The host image is all `linux/amd64`, however what is produced, the sentry-cli binary, is for a given tagged release.
We do not have `aarch64` build yet, but you can track it here https://github.com/getsentry/sentry-cli/issues/1338 (which also reports that it's working fine).
I'll close this one as a duplicate of above issue, as they are effectively the same.

**Closed by kamilogorek** 2022-11-29 16:46 UTC

**Comment by koreno** [comment] 2022-11-29 18:26
My point is that it is not possible to build a sentry-cli binary with the given docker file.
When I change the `FROM getsentry/rust-musl-cross` to `FROM messense/rust-musl-cross` things work properly.

**Comment by kamilogorek** [comment] 2022-11-29 18:29
It's because `messense` has all archs supported, we don't yet, which the issue above tracks :)

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1523305/204615433-b7f01146-e0f7-46f9-b6f3-5079bdd5ba57.png">

https://hub.docker.com/r/messense/rust-musl-cross/tags

**Comment by hxgqh** [comment] 2023-10-15 23:40
> It's because `messense` has all archs supported, we don't yet, which the issue above tracks :)
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/1523305/204615433-b7f01146-e0f7-46f9-b6f3-5079bdd5ba57.png">
> 
> https://hub.docker.com/r/messense/rust-musl-cross/tags
> 
> You are asking for `linux/arm64/v8`, and we do have `linux/amd64` only now.

Linux/arm64 is the same as linux/arm64/v8?
