### ISSUE TITLE
sentry-cli binary is not downloaded using Yarn PnP

### ISSUE THREAD

**Issue by mzvonar** [getsentry/sentry-cli#900] opened 2021-02-04 09:39 UTC
### Environment
Yarn 2 with Plug 'n' Play on OS X

How do you use Sentry?
`Sentry SaaS (sentry.io)`

Which SDK and version?
`@sentry/cli 1.62.0`

### Steps to Reproduce

1. Install @sentry/cli with yarn pnp
2. Run `yarn run @sentry/cli`

### Expected Result

@sentry/cli should have downloaded `sentry-cli` binary during installation. sentry-cli should start

### Actual Result

`sentry-cli` binary is not found.
Install script is not run by yarn when using PnP and thus `sentry-cli` binary is not downloaded.
I'm able to download the binary if I unplug @sentry/cli and then run `yarn rebuild @sentry/cli`.

Yarn prints out this during rebuild:
`@sentry/cli@npm:1.62.0 must be built because it never did before or the last one failed`.

It looks like yarn doesn't run install script inside @sentry/cli package at all. I wasn't able to find any trace of error during installation. 
This works with Yarn 2 with PnP disabled. When I then switched to PnP the install script was run so it might be something with yarn not detecting the need of rebuilding the package. That's how I found out that running `yarn rebuild @sentry/cli` helps.

**Comment by merceyz** [comment] 2021-02-05 13:59
Hey, one of the Yarn maintainers here :wave: 

Just checked to be sure and it works as expected
```sh
yarn init -y2
yarn add @sentry/cli
yarn sentry-cli --version
# -> sentry-cli 1.62.0
```

> Run yarn run @sentry/cli

That should be `yarn sentry-cli` or `yarn run sentry-cli`

> It looks like yarn doesn't run install script inside @sentry/cli package at all

It does, that's the `... must be built ...` message you see

**Comment by mzvonar** [comment] 2021-02-05 15:21
> Hey, one of the Yarn maintainers here 👋
> 
> Just checked to be sure and it works as expected
> 
> ```shell
> yarn init -y2
> yarn add @sentry/cli
> yarn sentry-cli --version
> # -> sentry-cli 1.62.0
> ```
> 
> > Run yarn run @sentry/cli
> 
> That should be `yarn sentry-cli` or `yarn run sentry-cli`
> 
> > It looks like yarn doesn't run install script inside @sentry/cli package at all
> 
> It does, that's the `... must be built ...` message you see

Hi, thanks for help @merceyz 
While I was migrating to yarn 2 and fixing various issues I deleted .yarn/cache and .yarn/unplugged folders a few times.
Running `yarn install` then doesn't run install script inside @sentry/cli again. Yarn thinks that the package has already been built.
Is this expected behaviour? Maybe I shouldn't be deleting `.yarn/unplugged`, but if I want to do clean install what is the correct way? Should I delete something else, like `.pnp.js`?
Sorry it seems like this is yarn related issue.

**Comment by merceyz** [comment] 2021-02-05 15:37
> While I was migrating to yarn 2 and fixing various issues I deleted .yarn/cache and .yarn/unplugged folders a few times. [...] Is this expected behaviour?

Ah, that explains it, i'm able to reproduce now so this seems like a bug on our end so you can probably close this and open one in https://github.com/yarnpkg/berry.

> Maybe I shouldn't be deleting .yarn/unplugged

It's perfectly fine to delete it, you shouldn't have to, but you're more than welcome to.

> but if I want to do clean install what is the correct way? Should I delete something else, like .pnp.js?

The info containing what has been built is located in `.yarn/build-state.yml` (for now), deleting that (or running `yarn rebuild`) will force all install scripts to run again. There is no reason to manually delete `.pnp.js`, since it's really cheap to generate it's written on each install so its state does not affect the install at all.

Until we fix the build state issue `rm -rf .yarn/unplugged .yarn/build-state.yml && yarn` should be enough

**Closed** 2021-02-08 12:03 UTC
