### ISSUE TITLE
Install script creates a lot of blank lines in CI environment

### ISSUE THREAD

**Issue by jlenos** [getsentry/sentry-cli#530] opened 2019-05-15 14:46 UTC
When installing the Sentry CLI in a CI environment I am seeing over 700 blank lines following the "fetching" lines.

Is there any way to suppress the output?
I have already tried using the SENTRY_NO_PROGRESS_BAR environment variable.

Example using CircleCI and npm 6.9.0:

```
> @sentry/cli@1.41.1 install /home/circleci/ifc/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Linux-x86_64  25% 0.1sfetching sentry-cli-Linux-x86_64  49% 0.0sfetching sentry-cli-Linux-x86_64  72% 0.0sfetching sentry-cli-Linux-x86_64  96% 0.0sfetching sentry-cli-Linux-x86_64  100% 0.0s












...
```

**Comment by tonyo** [comment] 2019-05-16 07:58
Is the issue still there when using more recent versions of `sentry-cli`, e.g. 1.43.0?

**Comment by jlenos** [comment] 2019-05-16 23:55
I just tested with 1.43.0 and got the same issue:

```
> @sentry/cli@1.43.0 install /home/circleci/ifc/node_modules/@sentry/cli
> node scripts/install.js

fetching sentry-cli-Linux-x86_64  20% 0.1sfetching sentry-cli-Linux-x86_64  43% 0.0sfetching sentry-cli-Linux-x86_64  67% 0.0sfetching sentry-cli-Linux-x86_64  71% 0.0sfetching sentry-cli-Linux-x86_64  89% 0.0sfetching sentry-cli-Linux-x86_64  95% 0.0sfetching sentry-cli-Linux-x86_64  100% 0.0s







...
```

**Comment by kamilogorek** [comment] 2020-03-05 15:17
This was caused by the incorrect download progress bar. It's fixed now, and if necessary can bo completely supressed with yarns `--silent` flag or npms `--loglevel silent`

**Closed by kamilogorek** 2020-03-05 15:17 UTC
