### ISSUE TITLE
Using sentry-cli uploaded soucemaps and always alert "error: API request failed and SSL connect error"

### ISSUE THREAD

**Issue by ChihYungChang** [getsentry/sentry-cli#1921] opened 2024-01-30 10:35 UTC
![image](https://github.com/getsentry/sentry-cli/assets/40090591/be7bc402-0a47-4240-8861-825366d99ebf)

Using sentry-cli uploaded soucemaps and always alert:
error: API request failed
caused by: [35] SSL connect error (Server aborted the SSL handshake)

Environment:
node: v18.19.0
npm: v10.2.3
@sentry/cli: 2.26.0
@sentry/webpack-plugin: 2.10.3

OS:
Apple M3 Max macOS Sonoma

**Comment by szokeasaurusrex** [comment] 2024-01-30 13:17
@ChihYungChang based on the error message, it seems that there may be an issue with your network connection or proxy configuration (if you are using a proxy). 

Please try running the command that produced the error again, in case the problem has resolved itself. If the problem is still ongoing, please run the following command to confirm whether there is a network issue:
```bash
$ curl -X POST https://sentry.io/api/0/projects/pixel-order/qingtian-xr/releases/
```

If above command produces the same error message as the `sentry-cli` command, then there is most likely a network problem. Otherwise, please let me know what the output from the `curl` command is, so I can better understand what is going on.

**Comment by ChihYungChang** [comment] 2024-01-31 06:56
@szokeasaurusrex  <img width="570" alt="image" src="https://github.com/getsentry/sentry-cli/assets/40090591/f0451dc2-6892-40bb-b022-786b421b8d05">

**Comment by szokeasaurusrex** [comment] 2024-01-31 10:10
@ChihYungChang I think you probably have some issue with your network setup, since the error message you observe from the `curl` command indicates that there is some problem connecting with the server. When I run the same command, I receive the following output:
```
user@host ~ % curl -X POST https://sentry.io/api/0/projects/pixel-order/qingtian-xr/releases/
{"detail":"Authentication credentials were not provided."}
```

My output indicates that I was able to reach the server, since the server replied that my authentication credentials were missing, which is expected because this `curl` command makes an empty `POST` request. 

I would recommend checking your system's and network's proxy and firewall settings to check whether they may be blocking you from accessing our server. You could also try using a different network.

**Comment by ChihYungChang** [comment] 2024-01-31 10:40
@szokeasaurusrex 
If I activate the global proxy, it becomes as follows:
<img width="569" alt="image" src="https://github.com/getsentry/sentry-cli/assets/40090591/d5a7df29-8677-46c6-81ee-0250e499bfa2">

**Comment by szokeasaurusrex** [comment] 2024-01-31 10:52
As long as your output for the `curl` command is different from mine, you most likely still have a problem with your network configuration because any other error message would indicate that you are unable to connect with the `sentry.io` server.

Unfortunately, it is extremely difficult for me to assist with resolving this problem, since it is likely specific to your network configuration, which I am unfamiliar with. If you continue to struggle debugging this problem, I would suggest reaching out to your network administrator, since they are the ones who would be able to help you.

**Comment by ChihYungChang** [comment] 2024-01-31 11:43
Oh! I have resolved it, the Mac console did not go through proxy requests.

Need to be in ~/.zshrc, configure the following proxy address:
```bash
export https_proxy=http://127.0.0.1:xxxx http_proxy=http://127.0.0.1:xxxx all_proxy=socks5://127.0.0.1:xxxx 
```

<img width="571" alt="image" src="https://github.com/getsentry/sentry-cli/assets/40090591/c60766c2-eec3-48c2-a114-d93edecaabe9">

**Comment by szokeasaurusrex** [comment] 2024-01-31 12:06
Okay, is the Sentry CLI working now? @ChihYungChang

**Comment by szokeasaurusrex** [comment] 2024-01-31 13:02
Great, then I will close the issue!

**Closed by szokeasaurusrex** 2024-01-31 13:02 UTC
Labels: Waiting for: Product Owner
