### ISSUE TITLE
Web deobfuscation not working with `url_prefix`

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-cli#2074] opened 2024-05-31 12:32 UTC
### CLI Version

2.27.0

### Operating System and Architecture

- [X] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.3.1

### CLI Command

/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "files" "sentry_flutter_example@8.2.0" "upload-sourcemaps" "/Users/denis/Repos/sentry/sentry-dart/flutter/example/build/web" "--ext" "map" "--ext" "js" "--wait" "--url-prefix" "~/foo/

### Exact Reproduction Steps

We are currently adding `url_prefix` to the `Sentry Dart Plugin`, which uses `senrty-cli`. For testing, we build the web version of the `sentry-dart` flutter example.

https://github.com/getsentry/sentry-dart-plugin/pull/222

Setup plugin from PR

```yaml
  sentry_dart_plugin:
    path: ../../../forks/joyds/sentry-dart-plugin
```

add the prefix to the plugin config

 ```yaml
  url_prefix: ~/foo/
 ```

build the web version

```bash
flutter build web --base-href=/foo/ --source-maps
```

run the plugin

```
flutter pub run sentry_dart_plugin
```

Move build files into `foo` subfolder and start a local webserver.

```bash
python3 -m http.server
```

Trigger a couple of issues and check on sentry.io

### Expected Results

Deobfuscated stacktraces with correct url prefix.

### Actual Results

[Issue](https://sentry-sdks.sentry.io/issues/5432582273/events/423d01e1fad64765b124af1a248d9333/?project=5428562&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=next-event&statsPeriod=1h&stream_index=0)

<img width="837" alt="Bildschirmfoto 2024-05-31 um 11 14 56" src="https://github.com/getsentry/sentry-dart-plugin/assets/3984453/0ccc28da-5b66-45ed-a12e-6ed4d22ed984">

[Source Maps](https://sentry-sdks.sentry.io/settings/projects/sentry-flutter/source-maps/artifact-bundles/9ffe95e4-3ee6-561c-bcf8-bdd24d19d351/)

<img width="1506" alt="Bildschirmfoto 2024-05-31 um 11 14 31" src="https://github.com/getsentry/sentry-dart-plugin/assets/3984453/f8ccc8d3-8f74-406f-ba15-edb63ae25f08">

The prefix is missing in the url which is shown in the ST. The symbol maps were uploaded and showing as expected.

### Logs

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
retrieving config from pubspec.yaml

Downloading Sentry CLI 2.27.0 from https://downloads.sentry-cdn.com/sentry-cli/2.27.0/sentry-cli-Darwin-universal to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli

Sentry CLI binary checksum verification passed successfully (hash: 8693527282890285f55d9b55414905e8621dd788ad3ae4c85175b84e8eeb6a04).

Sentry CLI downloaded successfully.
☑ reading config values                                                             
☑ validating config values                                                             
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
INFO    2024-05-31 11:12:46.259119 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "debug-files" "upload" "--org" "sentry-sdks" "--project" "sentry-flutter" "--include-sources" "/Users/denis/Repos/sentry/sentry-dart/flutter/example" "--wait"
  INFO    2024-05-31 11:12:46.259387 +02:00 Issuing a command for Organization: sentry-sdks Project: sentry-flutter

> Found 128 debug information files

> Resolved source code for 36 debug information files

> Prepared debug information files for upload

> Nothing to upload, all files are on the server
☑ uploading debug symbols                                                             

INFO    2024-05-31 11:12:54.771078 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "new" "sentry_flutter_example@8.2.0+69"

Created release sentry_flutter_example@8.2.0+69
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 27% uploading source maps..                               
INFO    2024-05-31 11:12:55.391052 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "files" "sentry_flutter_example@8.2.0+69" "upload-sourcemaps" "/Users/denis/Repos/sentry/sentry-dart/flutter/example/build/web" "--ext" "map" "--ext" "js" "--dist" "69" "--wait" "--url-prefix" "~/foo/"

> Found 8 files

> Analyzing 8 sources

> Rewriting sources

> Adding source map references

> Bundled 8 files for upload
> Bundle ID: 115147ee-4f9f-5800-b505-2e8e4b1d3631

> Uploaded files to Sentry

> File processing complete
> Organization: sentry-sdks
> Project: sentry-flutter
> Release: sentry_flutter_example@8.2.0+69
> Dist: 69
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/foo/flutter_service_worker.js
  Minified Scripts
    ~/foo/canvaskit/canvaskit.js (sourcemap at ../main.dart.js.map)
    ~/foo/canvaskit/chromium/canvaskit.js (sourcemap at ../../main.dart.js.map)
    ~/foo/canvaskit/skwasm.js (sourcemap at ../main.dart.js.map)
    ~/foo/canvaskit/skwasm.worker.js (sourcemap at ../main.dart.js.map)
    ~/foo/flutter.js (sourcemap at flutter.js.map)
    ~/foo/main.dart.js (sourcemap at main.dart.js.map)
  Source Maps
    ~/foo/main.dart.js.map

INFO    2024-05-31 11:13:00.604978 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "files" "sentry_flutter_example@8.2.0+69" "upload-sourcemaps" "/Users/denis/Repos/sentry/sentry-dart/flutter/example" "--ext" "dart" "--dist" "69" "--wait"

> Found 13 files

> Analyzing 13 sources

> Rewriting sources
> Adding source map references

> Bundled 13 files for upload
> Bundle ID: 9ffe95e4-3ee6-561c-bcf8-bdd24d19d351

> Uploaded files to Sentry

> File processing complete
> Organization: sentry-sdks
> Project: sentry-flutter
> Release: sentry_flutter_example@8.2.0+69
> Dist: 69
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/integration_test/all.dart
    ~/integration_test/integration_test.dart
    ~/integration_test/profiling_test.dart
    ~/lib/auto_close_screen.dart
    ~/lib/drift/connection/connection.dart
    ~/lib/drift/connection/native.dart
    ~/lib/drift/connection/unsupported.dart
    ~/lib/drift/database.dart
    ~/lib/drift/database.g.dart
    ~/lib/isar/user.dart
    ~/lib/isar/user.g.dart
    ~/lib/main.dart
    ~/lib/user_feedback_dialog.dart
☑ uploading source maps                                                             

INFO    2024-05-31 11:13:04.370775 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "set-commits" "sentry_flutter_example@8.2.0+69" "--auto" "--ignore-missing"

INFO    2024-05-31 11:13:05.313937 +02:00 Resolving HEAD (adinauer/sentry-java@HEAD)

INFO    2024-05-31 11:13:05.328913 +02:00 Resolving HEAD (Lms24/sveltekit-vercel@HEAD)

INFO    2024-05-31 11:13:05.334079 +02:00 Resolving HEAD (malwilley/sentry@HEAD)

INFO    2024-05-31 11:13:05.334285 +02:00 Resolving HEAD (malwilley/sentry-react-native@HEAD)

INFO    2024-05-31 11:13:05.334464 +02:00 Resolving HEAD (origin@HEAD)

Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.

No commits found. Leaving release alone. If you believe there should be some, change commits range or initial depth and try again.

INFO    2024-05-31 11:13:06.852588 +02:00 sentry-cli was invoked with the following command line: "/Users/denis/Repos/sentry/sentry-dart/flutter/example/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--log-level" "info" "releases" "--org" "sentry-sdks" "--project" "sentry-flutter" "finalize" "sentry_flutter_example@8.2.0+69"

Finalized release sentry_flutter_example@8.2.0+69

**Comment by szokeasaurusrex** [comment] 2024-05-31 14:25
@denrase, from looking at this issue and the PR you linked (getsentry/sentry-dart-plugin#222), and from my (limited) understanding of how sourcemaps work, it seems more likely than not that this issue is caused by something other than the Sentry CLI. 

According to your issue report, the Sentry CLI is correctly prepending the `~/foo/` prefix, and the sourcemaps are showing up in Sentry as expected, with the correct prefix. Since the CLI is only responsible for uploading the sourcemaps, it therefore seems to me that it has done its job correctly.

If I understand the issue correctly, it seems that the reason the stack traces are not being de-minified is because the stack trace URL does not contain the URL prefix. My guess is that this is because of either a misconfiguration in the Flutter app itself, or a bug in Sentry. If we view the raw stack trace of the Sentry issue you linked, we observe that the stack trace does not contain the prefix:

```
minified:oO: Exception: Throws onPressed
  at c(main.dart.js:5123:28)
  at a_(main.dart.js:5132:16)
  at $0(main.dart.js:98342:17)
  at XO(main.dart.js:57802:16)
  at <fn>(main.dart.js:5258:79)
  at Yk(main.dart.js:54576:11)
  at d4(main.dart.js:54580:23)
  at XQ(main.dart.js:54740:16)
  at OD(main.dart.js:54711:5)
  at XN(main.dart.js:54674:5)
  at ix(main.dart.js:54638:18)
  at <fn>(main.dart.js:5259:65)
  at a9q(main.dart.js:54532:9)
  at $2(main.dart.js:54544:37)
  at a7(main.dart.js:43810:20)
  at Pr(main.dart.js:54539:15)
  at a_4(main.dart.js:54537:16)
  at kU(main.dart.js:53665:10)
  at aos(main.dart.js:53659:11)
  at QH(main.dart.js:53653:6)
  at JS(main.dart.js:53643:8)
  at FE(main.dart.js:53641:43)
  at acJ(main.dart.js:53629:15)
  at <fn>(main.dart.js:5259:65)
  at aCl(main.dart.js:6783:11)
  at <fn>(main.dart.js:100808:13)
  at pF(main.dart.js:45219:14)
  at pG(main.dart.js:45196:12)
  at pd(main.dart.js:1950:10)
  at asR(main.dart.js:37876:5)
  at <fn>(main.dart.js:5260:67)
  at qk(main.dart.js:37922:30)
  at $1(main.dart.js:38168:5)
  at $1(main.dart.js:38126:37)
  at $1(main.dart.js:37925:43)
  at b_p(main.dart.js:5085:71)
  at aLr(main.dart.js:7757:24)
  at b3K(main.dart.js:9233:22)
  at <fn>(main.dart.js:9229:43)
```

Which makes me think that either the stack trace should include the prefix, or perhaps, you should not be using the url prefix option when uploading the sourcemaps.

Please let me know whether that helps.

**Comment by denrase** [comment] 2024-06-03 10:43
@szokeasaurusrex Thanks for the response. I think you are correct, not much more sentry-cli can do.  I'm also not aware that we should prepend the prefix on the SDK side, can you maybe point me to someone that might know more about how sentry handles the prefix in the web UI?

**Comment by szokeasaurusrex** [comment] 2024-06-03 14:08
@getsentry/team-web-sdk-frontend maintains the JavaScript SDK, perhaps they can help here

**Comment by buenaflor** [comment] 2024-06-19 12:10
We can close this since the fix has to be done on the dart sdk and not the cli

**Closed by buenaflor** 2024-06-19 12:10 UTC
