### ISSUE TITLE
After yarn install, still cannot find @sentry/cli

### ISSUE THREAD

**Issue by jgfidelis** [getsentry/sentry-cli#407] opened 2018-10-03 21:37 UTC
My package.json:

```
"dependencies": {
...
"react-native-sentry": "^0.39.0",
},
"devDependencies": {
    "@babel/core": "7.1.2",
    "@babel/runtime": "7.1.2",
    "@babel/plugin-proposal-export-default-from": "7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "7.0.0",
    "@commitlint/cli": "^6.2.0",
    "@commitlint/config-conventional": "^6.1.3",
    "@sentry/cli": "^1.35.5",
...
}
```

I can post the whole thing if it helps.

Even after removing `yarn.lock`, after `yarn install` the folder `node_modules/@sentry` does not exist.

I tried to clean cache with `yarn cache clean && yarn install` but it did not help
yarn version: `1.10.1`

Possibly related to: https://github.com/getsentry/react-native-sentry/issues/323

Can anyone give us an insight?

**Comment by mxstbr** [comment] 2018-10-05 13:31
Also running into this, but funnily enough only in CI: https://circleci.com/gh/withspectrum/spectrum/15580

**Comment by jan-auer** [comment] 2018-10-05 14:21
@jgfidelis I'm not able to reproduce this right now. Would be interesting to see if this also happens when you run `npm install` instead of yarn? 

@mxstbr Your error is different, it's not able to verify the sentry-cli version after the binary has downloaded successfully. Any chance you have overridden `SENTRYCLI_CDNURL`? From your build I'm not able to see which package version is in the lock file -- is it 1.36.1?

**Comment by mxstbr** [comment] 2018-10-05 15:17
Resolved by explicitly adding `@sentry/cli@latest` to the package.json—for some reason when installed as a dep of `sentry-expo` it failed, but when I added explicitly added it it worked 🤷‍♂️

**Comment by kamilogorek** [comment] 2020-03-05 13:40
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Closed by kamilogorek** 2020-03-05 13:40 UTC
