### ISSUE TITLE
"A project slug is required" for upload-sourcemaps in GitLab CI

### ISSUE THREAD

**Issue by axnsan12** [getsentry/sentry-cli#451] opened 2018-12-12 22:39 UTC
```console
$ sentry-cli releases files $VERSION upload-sourcemaps --rewrite ./dist/ --url-prefix /usr/src/app/
Analyzing 4 sources
Rewriting sources
Adding source map references
error: A project slug is required

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
```

This seems related to #95. The release was previously created using ``sentry-cli``.

```console
$ sentry-cli releases new -p $PROJECT $VERSION
Created release c4ea65d6fd63f468eb69ac3a9d996c1f9521c764.
$ sentry-cli releases set-commits --auto $VERSION
+---------------+--------------+
| Repository    | Revision     |
+---------------+--------------+
| < REPO NAME > | c4ea65d6fd63 |
+---------------+--------------+
```

**Comment by hamadmj** [comment] 2018-12-24 09:17
Can confirm the same issue. Is there a workaround to this?

**Comment by axnsan12** [comment] 2018-12-24 09:19
The command doesn't seem to accept a project slug argument, but you can export the ``SENTRY_PROJECT`` envelope variable and it will be picked up.

**Comment by Yankovsky** [comment] 2019-04-16 09:41
Can you add --project option to `sentry-cli releases files upload-sourcemaps`?
Or tell me where should it be.
It is very strange that SENTRY_PROJECT env variable should be declared and there is no option to specify project in command.

**Comment by EddyP23** [comment] 2019-08-01 08:25
Same here. Very weird on two fronts. It's been 8 months and no fix came out for a reasonably simple bug. And also docs don't mention this. Sad.

**Comment by MrGWest** [comment] 2019-08-06 05:47
So the problem is not due to having more than on project released? My CircleCI config has the following line `sentry-cli releases new -p node-server -p web-client $CIRCLE_SHA1`.

**Comment by Meeeeow** [comment] 2019-11-12 06:13
Same error message here, a `SENTRY_PROJECT` environment variable was dynamic exported at same stage, tested work with echo, but sentry cli says "project slug is required".

Temporary solution is write everything include token and project name in a `.sentryclirc` and delete it after source map uploaded

**Comment by rtyshyk** [comment] 2019-11-29 14:35
@Meeeeow 
Works fine for me with env variables.
```yml
  variables:
    SENTRY_URL: https://selfhosted/
    SENTRY_ORG: org
    SENTRY_AUTH_TOKEN: SECRET
    SENTRY_PROJECT: projectname
  script:
    - cd app
    - npm install --loglevel warn
    - npm run build
    - mv dist/config.js.example dist/config.js
    - HASH=`git log --pretty="%h" -n1 HEAD`
    - VERSION=$CI_COMMIT_REF_NAME.$HASH
    - sed -i -e "s,%APP_VERSION%,$VERSION,g" dist/config.js
    # create release in sentry
    - sentry-cli releases new -p $SENTRY_PROJECT $VERSION
    - sentry-cli releases set-commits --auto $VERSION
    - sentry-cli releases files $VERSION upload-sourcemaps dist
```

**Comment by Meeeeow** [comment] 2019-12-02 06:03
@rtyshyk In my case, `SENTRY_PROJECT` was dynamic exported by a executable in script section, not defined in CI configuration.

**Comment by kamilogorek** [comment] 2020-03-05 14:03
Related to/Duplicate of https://github.com/getsentry/sentry-cli/issues/179
Let's track flags related issues there.

**Closed by kamilogorek** 2020-03-05 14:03 UTC

**Comment by mediafreakch** [comment] 2020-03-20 19:18
Just run into this. It's very odd that you need to define a project name when creating releases, but cannot pass one on cli options when uploading sourcemaps... Neither the cli help nor the docs mention this!

For anyone else that comes along. This combination works:
- `export SENTRY_PROJECT=yourproject`
- `export SENTRY_AUTH_TOKEN=authtoken`
- `sentry-cli releases -o your-organization new 1.4.0 --finalize`
- `sentry-cli releases -o your-organization files 1.4.0 upload-sourcemaps -x map ./dist/js`

What is still fuzzy to me is whether the version (1.4.0 in this case) needs to be unique across the org. Docs are unclear about this and given that you have to specify SENTRY_PROJECT I would assume that is obsolete. Can anybody confirm?

**Comment by kamilogorek** [comment] 2020-03-21 15:02
Releases are scoped per project, so they don't need to be unique across the whole organization.

**Comment by kamilogorek** [comment] 2020-03-21 18:43
>  It's very odd that you need to define a project name when creating releases, but cannot pass one on cli options when uploading sourcemaps...

You can pass it with `-p` or `--project` flag:

```terminal
sentry-cli releases -p your-project -o your-organization files 1.4.0 upload-sourcemaps -x map ./dist/js
```

> What is still fuzzy to me is whether the version (1.4.0 in this case) needs to be unique across the org. Docs are unclear about this and given that you have to specify SENTRY_PROJECT I would assume that is obsolete. Can anybody confirm?

Releases are scoped per organization, so they need to be unique across the whole organization. We recommend prefixing your releases with the `<project name>@<version>`

**Comment by troZee** [comment] 2023-12-06 10:05
Relates to https://github.com/getsentry/sentry-wizard/issues/512
