### ISSUE TITLE
npm install failed with Windows

### ISSUE THREAD

**Issue by ccksfh** [getsentry/sentry-cli#546] opened 2019-06-10 01:55 UTC
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.12.0
6.4.1
EcrmApp@0.0.1 Q:\EcrmApp
+-- @sensors.data/react-native-sensors-analytics@1.0.0
+-- axios@0.18.0
+-- husky@1.3.1
+-- jsc-android@236355.1.1
+-- mobx@4.8.0
+-- mobx-react@5.4.3
+-- react@16.6.3
+-- react-native@0.58.6
+-- react-native-config@0.11.7
+-- react-native-gesture-handler@1.1.0
+-- react-native-splash-screen@3.2.0
+-- react-native-webview@5.8.1
`-- react-navigation@3.5.1

```

---
I have following issue:

Description goes here 
```
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1246 verbose stack Error: @sentry/cli@1.44.3 install: `node scripts/install.js`
1246 verbose stack Exit status 1
1246 verbose stack     at EventEmitter.<anonymous> (C:\Users\ck\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
1246 verbose stack     at emitTwo (events.js:126:13)
1246 verbose stack     at EventEmitter.emit (events.js:214:7)
1246 verbose stack     at ChildProcess.<anonymous> (C:\Users\ck\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1246 verbose stack     at emitTwo (events.js:126:13)
1246 verbose stack     at ChildProcess.emit (events.js:214:7)
1246 verbose stack     at maybeClose (internal/child_process.js:915:16)
1246 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1247 verbose pkgid @sentry/cli@1.44.3
1248 verbose cwd Q:\EcrmApp
1249 verbose Windows_NT 10.0.17134
1250 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-sentry"
1251 verbose node v8.12.0
1252 verbose npm  v6.4.1
1253 error code ELIFECYCLE
1254 error errno 1
1255 error @sentry/cli@1.44.3 install: `node scripts/install.js`
1255 error Exit status 1
1256 error Failed at the @sentry/cli@1.44.3 install script.
1256 error This is probably not a problem with npm. There is likely additional logging output above.
1257 verbose exit [ 1, true ]
```

**Steps to reproduce:**
- npm install react-native-sentry --save
- I've tried @0.42.0 & lastest, all failed
- MacOS is ok

**Actual result:**
- failed

**Expected result:**
- success

**Comment by JakubKoralewski** [comment] 2019-06-28 14:12
Similar problem here. Fails on TravisCI with version 1.46.0:
```
npm WARN engine agent-base@4.3.0: wanted: {"node":">= 4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
> @sentry/cli@1.46.0 install /home/travis/build/JakubKoralewski/mireks/node_modules/@nuxtjs/sentry/node_modules/@sentry/webpack-plugin/node_modules/@sentry/cli
> node scripts/install.js
/home/travis/build/JakubKoralewski/mireks/node_modules/@nuxtjs/sentry/node_modules/@sentry/webpack-plugin/node_modules/@sentry/cli/scripts/install.js:5
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm WARN engine @sentry/minimal@5.4.3: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine @sentry/types@5.4.2: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine @sentry/utils@5.4.2: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine @sentry/core@5.4.3: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine @sentry/hub@5.4.3: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine @sentry/minimal@5.4.3: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/travis/.nvm/v0.10.48/bin/node" "/home/travis/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @sentry/cli@1.46.0 install: `node scripts/install.js`
npm ERR! Exit status 8
```

**Comment by mitsuhiko** [comment] 2019-07-09 07:47
I cannot reproduce this issue at all but given the thumbs up I assume others are having this as well. Are you using a virus scanner by any chance or something else that might hook into the execution of binaries?

**Comment by tfaieta** [comment] 2019-07-10 19:30
Happening on MacOS 10.14.6 Beta as well.

**Comment by biaji** [comment] 2019-07-12 03:40
We got the same issue.  It look like install.js has some flaw in proxy setting.

`
  const proxyUrl = Proxy.getProxyForUrl(downloadUrl);
  const agent = proxyUrl ? new HttpsProxyAgent(proxyUrl) : null;
`

proxyUrl got null in our case. Which caused the download failed.

**Comment by ccksfh** [comment] 2019-07-19 02:34
> I cannot reproduce this issue at all but given the thumbs up I assume others are having this as well. Are you using a virus scanner by any chance or something else that might hook into the execution of binaries?

I've checked my virus scanner but nothing was found & blocked. I solved this by `npm install --sentrycli_cdnurl=https://npm.taobao.org/mirrors/sentry-cli/`

**Comment by kamilogorek** [comment] 2020-03-05 15:14
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue. 
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Closed by kamilogorek** 2020-03-05 15:14 UTC
