### ISSUE TITLE
`sentry-cli react-native appcenter`... keep failing due to Could not parse Info.plist file

### ISSUE THREAD

**Issue by fungilation** [getsentry/sentry-cli#476] opened 2019-02-06 06:06 UTC
I followed all the steps in https://docs.sentry.io/clients/react-native/codepush/. But I keep getting error on running:
```
$ appcenter codepush release-react -o ../WonderSwipe-bundle -s ../WonderSwipe-bundle/CodePush/main.jsbundle.map -p ./ios/WonderSwipe/Info.plist -d Production
Detecting ios app version:

Using the target binary version value "1.3.0" from "./ios/WonderSwipe/Info.plist".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest ../WonderSwipe-bundle/CodePush --bundle-output ../WonderSwipe-bundle/CodePush/main.jsbundle --dev false --entry-file index.js --platform ios --sourcemap-output ../WonderSwipe-bundle/CodePush/main.jsbundle.map
Loading dependency graph, done.
bundle: Writing bundle output to: ../WonderSwipe-bundle/CodePush/main.jsbundle
bundle: Writing sourcemap output to: ../WonderSwipe-bundle/CodePush/main.jsbundle.map
bundle: Done writing bundle output
bundle: Done writing sourcemap output
bundle: Copying 1 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Successfully released an update containing the "../WonderSwipe-bundle/CodePush" directory to the "Production" deployment of the "WonderSwipe" app.

$ sentry-cli react-native appcenter <owner>/WonderSwipe ios ../WonderSwipe-bundle/CodePush
  INFO    2019-02-05 21:51:33.715893 -08:00 Loaded config from ~/.sentryclirc
  INFO    2019-02-05 21:51:33.716815 -08:00 sentry-cli was invoked with the following command line: "sentry-cli" "react-native" "appcenter" "<owner>/WonderSwipe" "ios" "../WonderSwipe-bundle/CodePush"
> Fetching latest AppCenter deployment info
  INFO    2019-02-05 21:51:43.825849 -08:00 Skipping update nagger update check
error: Could not parse Info.plist file
  caused by: expected value at line 1 column 1
```

Env:
MacOS 10.13.6
appcenter-cli: 1.1.11
sentry-cli: 1.38.0
React Native: 0.57.8

**Comment by ivan-infro** [comment] 2019-02-06 11:10
Broken in sentry-cli 1.38.0

A temporary solution to the problem is to add in devDependencies
 "@sentry/cli": "1.37.4",

**Comment by bruno-garcia** [comment] 2019-02-06 12:34
I'm working on a fix right now

**Comment by oguzhandemiroz** [comment] 2019-02-06 13:00
> I'm working on a fix right now

When does v1.38.1 come?

**Comment by bruno-garcia** [comment] 2019-02-06 13:14
Coming out now, when this build is done: https://travis-ci.com/getsentry/sentry-cli

**Comment by bruno-garcia** [comment] 2019-02-06 13:26
New version is on GitHub releases and npm.
Closing this issue but feel free to reopen if something's wrong.

**Closed by bruno-garcia** 2019-02-06 13:26 UTC
Labels: bug

**Comment by fungilation** [comment] 2019-02-06 20:10
Thanks for the speedy bug fix! Works fine now.
