### ISSUE TITLE
"AppCenter CLI not found" error using the sentry-cli react-native appcenter ... command

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-cli#328] opened 2018-06-22 22:13 UTC
I get the following error when following what is described here:

https://github.com/getsentry/sentry-cli/issues/244#issuecomment-399427190

Command:

`sentry-cli react-native appcenter --deployment Dev [Redacted]/[Redacted] android ./codepushbuild`

Console Output:

\> Fetching latest AppCenter deployment info
error: AppCenter CLI not found

Install with `npm install -g appcenter-cli` and make sure it is on the PATH.

---

OS: Windows 10
Git Bash

$ npm list @ sentry/cli -g --depth=0
C:\Program Files\nodejs
`-- @sentry/cli@1.33.0

NOTE: A space was added between "@" and "sentry/cli" to workaround GitHub removing the string.

$ npm list appcenter-cli -g --depth=0
C:\Program Files\nodejs
`-- appcenter-cli@1.0.6

I am able to run the following command from the same directory, which appears to be the command the sentry-cli wants to execute when it errors:

`appcenter codepush deployment history Dev --app [Redacted]/[Redacted] --output json`

https://github.com/getsentry/sentry-cli/blob/7cc2566534108cdd4822af88b171f08bb8e8f86f/src/utils/appcenter.rs#L98

**Comment by jan-auer** [comment] 2018-06-23 07:06
Duplicate of https://github.com/getsentry/sentry-cli/issues/319

**Closed by jan-auer** 2018-06-23 07:06 UTC

**Comment by jan-auer** [comment] 2018-06-23 07:09
Let's please continue discussion in the linked issue. Thanks!
