### ISSUE TITLE
Add send-envelope command 

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-cli#1168] opened 2022-03-28 11:49 UTC
Add send-envelope command ([blocked by missing features in sentry-rust](https://github.com/getsentry/sentry-rust/issues/381))

    - given some file, send evelope with DSN - rust cannot create an envelope

**Comment by kamilogorek** [comment] 2022-03-30 12:23
Duplicate of https://github.com/getsentry/sentry-cli/issues/703

**Closed** 2022-04-01 11:25 UTC
Labels: enhancement, feature, blocked, Status: Backlog
