### ISSUE TITLE
CLI upload-dif stucks and causing machines to timeout on macOS11

### ISSUE THREAD

**Issue by grzegorzkrukowski** [getsentry/sentry-cli#1004] opened 2021-08-09 10:36 UTC
### Environment

How do you use Sentry?
GitHub virtual environments (Actions) - macOS10 and macOS11 machines
SentryCLI 1.68.0

Which SDK and version?
CLI

### Steps to Reproduce

On our GitHub machines we are uploading debug symbols to Sentry using CLI:
`sentry-cli --auth-token {auth_token} upload-dif "{dsyms_path}" --org {organization} --project {project}`

When calling it on macOS11 machines - it's causing machines to hit a timeout.
On macOS10 machines upload works and it's really fast, on macOS11 it stuck for over 30 minutes.
No errors or warnings are being thrown.

### Logs

I have been trying to get more info from Sentry CLI using --log-level trace to get as much info as I can.

With the highest possible log it looks like this:
`
DEBUG 2021-08-11 13:47:26.568848 +00:00 sentry-cli version: 1.68.0, platform: "darwin", architecture: "x86_64" INFO 2021-08-11 13:47:26.570640 +00:00 sentry-cli was invoked with the following command line: "sentry-cli" "--log-level" "trace" "--auth-token" "***" "upload-dif" "/Users/runner/work/archive/my.xcarchive/dSYMs" "--org" "ORG_NAME" "--project" "PROJECT_NAME" INFO 2021-08-11 13:47:26.571230 +00:00 Issuing a command for Organization: ORG_NAME Project: PROJECT_NAME`
And then nothing for 20 minutes until it gets killed by an external dogwatch due to timeout:
`Error: The operation was canceled.`

### Expected Result

The upload should succeed.

### Actual Result

Upload silently blocks the machine forever until it is getting killed by GitHub itself.

**Comment by kamilogorek** [comment] 2021-09-16 13:41
This sounds like a duplicate of https://github.com/getsentry/sentry-cli/issues/1015 so lets keep the discussion there

**Closed by kamilogorek** 2021-09-16 13:42 UTC
