### ISSUE TITLE
Add option for version in get-cli script

### ISSUE THREAD

**Issue by sourabhv** [getsentry/sentry-cli#477] opened 2019-02-06 10:09 UTC
Currently the 1.38.0 version is broken for us (react-native-sentry fails). And there is no way to specify version in the curl script. I had to host my own file.

**Comment by bruno-garcia** [comment] 2019-02-06 10:21
@sourabhv Could you please give a bit more detail on what's happening?
A repro would greatly help us troubleshoot and fix the issue.

**Comment by sourabhv** [comment] 2019-02-06 12:00
I don't have a lot of information but here's the part from our CI which might be helpful:

```
▸ Running script 'Bundle React Native code and images'

❌  error: Could not parse Info.plist file


** ARCHIVE FAILED **


The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/distiller/Library/Developer/......
(1 failure)
[01:24:14]: Exit status: 65
[01:24:14]: 
[01:24:14]: Maybe the error shown is caused by using the wrong version of Xcode
[01:24:14]: Found multiple versions of Xcode in '/Applications/'
[01:24:14]: Make sure you selected the right version for your project
[01:24:14]: This build process was executed using '/Applications/Xcode-10.1.app'
[01:24:14]: If you want to update your Xcode path, either
[01:24:14]: 
[01:24:14]: - Specify the Xcode version in your Fastfile
[01:24:14]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[01:24:14]: 
[01:24:14]: - Specify an absolute path to your Xcode installation in your Fastfile
[01:24:14]: ▸ xcode_select "/Applications/Xcode8.app"
[01:24:14]: 
[01:24:14]: - Manually update the path using
[01:24:14]: ▸ sudo xcode-select -s /Applications/Xcode.app
[01:24:14]: 

+---------------+------------------------------+
|              Build environment               |
+---------------+------------------------------+
| xcode_path    | /Applications/Xcode-10.1.app |
| gym_version   | 2.114.0                      |
| export_method | app-store                    |
| sdk           | iPhoneOS12.1.sdk             |
+---------------+------------------------------+

[01:24:14]: ▸ error: Could not parse Info.plist file
[01:24:14]: ▸   caused by: expected value at line 1 column 1```

**Comment by tonyo** [comment] 2019-02-06 12:17
Looks like a duplicate of https://github.com/getsentry/sentry-cli/issues/476, let's track this there.

**Closed by tonyo** 2019-02-06 12:17 UTC
Labels: bug
