### ISSUE TITLE
"release not found" while uploading sourcemaps

### ISSUE THREAD

**Issue by sHooKDT** [getsentry/sentry-cli#548] opened 2019-06-11 10:41 UTC
Hi, 1.44.2 and higher breaks deployment for me.
I get "error: release not found" when trying to upload sourcemaps.
Versions below work fine.
I enabled debug logging and saw a change in upload URL from `.../files` to `.../assemble` where server answers 404, so I think it's related.

Honestly, I am a bit confused to see such changes in patch(!!!) releases.

**Comment by jan-auer** [comment] 2019-06-11 12:52
Before uploading artifacts, `sentry-cli` should create non-existing releases. I'm not quite sure how this is happening, but we will investigate. It looks like a regression.

Out of curiosity, what is the release name you're trying to upload to?

**Comment by sHooKDT** [comment] 2019-06-11 13:10
The thing is I explicitly create a release before uploading, so it's 100% exist.

>Out of curiosity, what is the release name you're trying to upload to?

just like `prod-2019-06-11#18:08:48`

**Comment by jan-auer** [comment] 2019-06-11 21:13
This will be fixed in the next release. Thanks for surfacing this!

**Closed** 2019-06-11 21:12 UTC
