### ISSUE TITLE
debugId not injected into sourcemap only source file

### ISSUE THREAD

**Issue by tranan89** [getsentry/sentry-cli#1681] opened 2023-07-11 14:06 UTC
Hi

### Environment

What version of the CLI and what OS are you running?

I use this command in our dockerfile: `RUN curl -sL https://sentry.io/get-cli/ | bash`

### Steps to Reproduce

`RUN sentry-cli sourcemaps inject ${STATIC_FILES_PATH}`

### Expected/Actual Result

`debugId` is injected into `server.bundle.js` as expected but nothing is injected into the sourcemap. I have searched for everything containing debug as well as the id that `server.bundle.js` contains

server.bundle.js contains:
//# debugId=ff6bddbc-11f1-54bc-8c3a-2211c24f8f2f

### Logs

The injection should be done according to the logs, but nothing seems to have been added to the sourcemap, only the regular bundle.

<img width="815" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/1b2a0804-9053-49d2-914b-913769ae4ad8">
<img width="848" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/90be5b8d-e9cb-4330-a65f-d9647736aeed">

**Comment by kamilogorek** [comment] 2023-07-13 10:16
Would it be feasible for you to try out the latest master build? There are some improvements around injection, and there's a chance it's already fixed.

- run https://rustup.rs/
- clone the repo
- `cargo build`
- `./target/debug/sentry-cli sourcemaps inject ${STATIC_FILES_PATH}`

**Comment by tranan89** [comment] 2023-07-13 13:45
@kamilogorek thanks for fast response. I tried out master locally according to your instructions and then it worked 👍 

Please get back once this has been released and updated in `https://sentry.io/get-cli/` so I can test it in our automated workflow as well.

**Comment by hthr-lee** [comment] 2023-07-13 18:55
Are you by chance using `sentry-cli sourcemaps upload` after? I noticed that `sentry-cli sourcemaps inject` works as expected when I run the command locally and check on my file system. But when I run `upload` afterwards, the debug_id in the *.map files are all removed during the [rewriting sources](https://github.com/getsentry/sentry-cli/blob/master/src/utils/sourcemaps.rs#L591) step. I can get around this by adding the `--no-rewrite` option when running `upload` but not sure if this is going to cause other unintended side effects.

**Comment by tranan89** [comment] 2023-07-14 13:13
@hthr-lee You are completely right. In our automated workflow where it doesn't work we do upload as well without the `--no-rewrite` flag. I tested this locally as well now with master and it is just like you say that the uploaded sourcemap disappears during the upload unless I add `--no-rewrite`. And just like you I don't know if its fine to add that flag or not 😅.

I can also see the debug ids in the upload report even though they are removed from the sourcemap files that can be downloaded through the sentry ui.
<img width="989" alt="image" src="https://github.com/getsentry/sentry-cli/assets/8797144/f370d9bb-e265-41cd-8c15-392dd344d675">

**Comment by loewenheim** [comment] 2023-07-18 12:18
See https://github.com/getsentry/sentry-cli/issues/1685.

**Comment by jbub** [comment] 2023-07-19 09:45
> Are you by chance using `sentry-cli sourcemaps upload` after? I noticed that `sentry-cli sourcemaps inject` works as expected when I run the command locally and check on my file system. But when I run `upload` afterwards, the debug_id in the *.map files are all removed during the [rewriting sources](https://github.com/getsentry/sentry-cli/blob/master/src/utils/sourcemaps.rs#L591) step. I can get around this by adding the `--no-rewrite` option when running `upload` but not sure if this is going to cause other unintended side effects.

This seems to be exactly the case we are running into.

**Comment by AykutSarac** [comment] 2023-07-19 11:26
`--no-rewrite` argument worked for me as well.

**Comment by argmichael** [comment] 2023-08-02 16:23
> See #1685.

@loewenheim Just want to make sure that this is no longer an issue and has been fixed in 2.20.0?

**Comment by AykutSarac** [comment] 2023-08-02 16:24
I can confirm it has been fixed with 2.20.

**Closed** 2023-08-02 16:25 UTC

**Comment by tranan89** [comment] 2023-08-07 08:39
Thanks for fixing 🙏 
I have confirmed that it is working in our automated workflow as well now 🎉
