### ISSUE TITLE
NPM install fails behind proxy

### ISSUE THREAD

**Issue by ryh** [getsentry/sentry-cli#196] opened 2017-12-22 04:43 UTC
`npm install @sentry/cli` and `npm install sentry-cli-binary@1.25.0` both failed
tried http_proxy, global socks proxy (macOS 10.13 System Proxy Config), both got this

```
> sentry-cli-binary@1.25.0 install /Users/ryh/dev/react/chain-react-conf/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: 'github-production-release-asset-2e65be.s3.amazonaws.com',
  port: 443,
  localAddress: undefined }
```
same terminal ENV
```
curl -I https://github-production-release-asset-2e65be.s3.amazonaws.com
HTTP/1.1 200 Connection established

HTTP/1.1 403 Forbidden
x-amz-bucket-region: us-east-1
x-amz-request-id: C6CEAFC8442BD67E
x-amz-id-2: OzcLf+JdqFzRUfzBFPnGUVgxyUz/LOx8lFk/yztnEjwOankSH6ggQgZ5G5b14qpvmh8p2BrXZTQ=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Fri, 22 Dec 2017 04:52:22 GMT
Server: AmazonS3
```
while  brew install is OK (same proxy)
```
==> Installing sentry-cli from getsentry/tools
==> Downloading https://github.com/getsentry/sentry-cli/releases/download/1.26.1
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
🍺  /usr/local/Cellar/sentry-cli/1.26.1: 3 files, 8MB, built in 12 seconds
```

**Comment by jan-auer** [comment] 2017-12-22 20:24
First, `sentry-cli-binary` has been deprecated in favor of `@sentry/cli`. Please only use install latter:

```
npm install @sentry/cli
```

Second, could you please post the node version you are running on? Since homebrew is able to download and since follow the redirect from GitHub to Amazon S3, the problem is either in node or something is altering the `Location` header.

Finally, the URL you are tried to download manually with curl was incomplete. The script actually downloads from a redirect link at GitHub. If you like to try this out, you can run this command and should see the `Location` header. Then you can download from that URL:

```
$ curl -I https://github.com/getsentry/sentry-cli/releases/download/1.26.1/sentry-cli-Darwin-x86_64
[...]
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/51176043/804f89da-dc51-11e7-8fab-7d9c77b2b24e
[...]
```

If that doesn't work, please have a look at your proxy configuration.

**Comment by ryh** [comment] 2017-12-23 05:45
node v8.9.0 (installed via homebrew)
npm 5.6.0
I edited the issue quickly after I tried with `npm install @sentry/cli`
I am not trying to download manually, just for debug ( curl can connect the server instead of `ECONNRESET ` )
I can download cli with homebrew,  but some npm package using cli as dependence,
still fail with `npm install`

**Comment by ryh** [comment] 2017-12-25 07:18
looks like `github-production-release-asset-2e65be.s3.amazonaws.com.` CNAME to
`s3-1-w.amazonaws.com.` was poisoned by local dns which will cause  `https` cannot connect with TLS ( exception?event? is there one can be catched?)
 but still don't know why fail with global proxy.  
May be this is `https`'s issue.[install-sentry-cli#L176](https://github.com/getsentry/sentry-cli/blob/master/bin/install-sentry-cli#L176)  Thanks for help.
Have a great holiday.

**Comment by ryh** [comment] 2017-12-25 07:59
will following necessary for user? [From install-sentry-cli#L176
](https://github.com/getsentry/sentry-cli/blob/master/bin/install-sentry-cli#L176)

```js
fetch.get(downloadUrl, handleResponse).on('error', function(err) {
   if (err.code == "ECONNRESET"){
      console.log("\
        A connection was forcibly closed by a peer. \n\
        This normally results from a loss of the connection\n\
         on the remote socket due to a timeout or reboot. \n\
        FOR DEBUG:\n\
        nslookup s3-1-w.amazonaws.com\n\
        cat /etc/hosts | grep s3-1-w.amazonaws.com\n\
        ")
    }
    console.log(err);
```
error description  from https://nodejs.org/api/errors.html

**Comment by jan-auer** [comment] 2018-01-17 10:58
Looks like it's related to your local setup then, so I will close this for now. The error message you propose, is rather generic and points in the wrong direction (Amazon certainly did not timeout or reboot).

@HazAT we could consider adding a better error message in the future, though.

**Closed by jan-auer** 2018-01-17 10:58 UTC
