### ISSUE TITLE
Problem to sentry-cli realese  from gitlab

### ISSUE THREAD

**Issue by maxi-89** [getsentry/sentry-cli#1501] opened 2023-03-03 15:18 UTC
### Environment

Django 4.1, Sentry 1.71.0, Gitlab

### Steps to Reproduce

i created a job in my gitlab pipeline. This is my job:
sentry-release-production:
  stage: release
  image: registry.gitlab.com/juman-roots/lpf/frontend/sentry-cli:latest
  script:
    - apt-get update && apt-get install -y ca-certificates
    - rm /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
    - update-ca-certificates -f
    - export APP_RELEASE="[production]-${CI_COMMIT_TAG}"
    - export FROM_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)))
    - export TO_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags))
    - sentry-cli --version
    - sentry-cli repos list
    - sentry-cli releases -o "$SENTRY_ORG" set-commits --commit "juman-roots/minierp/backend@$FROM_GIT..$TO_GIT" "$APP_RELEASE"
    - sentry-cli releases -o "$SENTRY_ORG" deploys "$APP_RELEASE" new -e production
  only:
    - tags

### Actual Result

$ export APP_RELEASE="[production]-${CI_COMMIT_TAG}"
$ export FROM_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)))
$ export TO_GIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags))
$ sentry-cli --version
sentry-cli 1.71.0
$ sentry-cli repos list
+--------+------------------+-----+
| Name   | Provider         | URL |
+--------+------------------+-----+
| origin | Unknown Provider | -   |
+--------+------------------+-----+
$ sentry-cli releases -o "$SENTRY_ORG" set-commits --commit "juman-roots/minierp/backend@$FROM_GIT..$TO_GIT" "$APP_RELEASE"
error: Unknown repo 'juman-roots/minierp/backend'

how can i fix this error? how can i get the correct repo name?

**Comment by kamilogorek** [comment] 2023-03-03 15:28
You need to have a repository configured in your project settings if you want to use automatic detection - https://docs.sentry.io/product/releases/setup/release-automation/

Alternatively without it - https://docs.sentry.io/product/cli/releases/#alternatively-without-a-repository-integration
And some manual steps if you want to go this route - https://docs.sentry.io/product/releases/associate-commits/

I'll close this issue, as this is not a bug nor feature request. If you have usage questions, please use our Discord. Thanks.

**Closed by kamilogorek** 2023-03-03 15:28 UTC
