### ISSUE TITLE
error while install sentry-cli :'Unterminated quoted string'

### ISSUE THREAD

**Issue by daidi** [getsentry/sentry-cli#1035] opened 2021-09-30 03:36 UTC
### Environment

How do you use Sentry?
on-premise 

### Steps to Reproduce

when install sentry-cli to the latest version, in cannot install properly:

`> @sentry/cli@1.69.0 install /usr/src/app/node_modules/@sentry/cli
> node scripts/install.js

info sentry-cli Downloading from https://npm.taobao.org/mirrors/sentry-cli//1.69.0/sentry-cli-Linux-x86_64
fetching sentry-cli-Linux-x86_64 1%
fetching sentry-cli-Linux-x86_64 2%
fetching sentry-cli-Linux-x86_64 3%
fetching sentry-cli-Linux-x86_64 4%
fetching sentry-cli-Linux-x86_64 5%
fetching sentry-cli-Linux-x86_64 6%
fetching sentry-cli-Linux-x86_64 7%
fetching sentry-cli-Linux-x86_64 8%
fetching sentry-cli-Linux-x86_64 9%
fetching sentry-cli-Linux-x86_64 10%
fetching sentry-cli-Linux-x86_64 11%
fetching sentry-cli-Linux-x86_64 12%
fetching sentry-cli-Linux-x86_64 13%
fetching sentry-cli-Linux-x86_64 14%
fetching sentry-cli-Linux-x86_64 15%
fetching sentry-cli-Linux-x86_64 16%
fetching sentry-cli-Linux-x86_64 17%
fetching sentry-cli-Linux-x86_64 18%
fetching sentry-cli-Linux-x86_64 19%
fetching sentry-cli-Linux-x86_64 20%
fetching sentry-cli-Linux-x86_64 21%
fetching sentry-cli-Linux-x86_64 22%
fetching sentry-cli-Linux-x86_64 23%
fetching sentry-cli-Linux-x86_64 24%
fetching sentry-cli-Linux-x86_64 25%
fetching sentry-cli-Linux-x86_64 26%
fetching sentry-cli-Linux-x86_64 27%
fetching sentry-cli-Linux-x86_64 28%
fetching sentry-cli-Linux-x86_64 29%
fetching sentry-cli-Linux-x86_64 30%
fetching sentry-cli-Linux-x86_64 31%
fetching sentry-cli-Linux-x86_64 32%
fetching sentry-cli-Linux-x86_64 33%
fetching sentry-cli-Linux-x86_64 34%
fetching sentry-cli-Linux-x86_64 35%
fetching sentry-cli-Linux-x86_64 36%
fetching sentry-cli-Linux-x86_64 37%
fetching sentry-cli-Linux-x86_64 38%
fetching sentry-cli-Linux-x86_64 39%
fetching sentry-cli-Linux-x86_64 40%
fetching sentry-cli-Linux-x86_64 41%
fetching sentry-cli-Linux-x86_64 42%
fetching sentry-cli-Linux-x86_64 43%
fetching sentry-cli-Linux-x86_64 44%
fetching sentry-cli-Linux-x86_64 45%
fetching sentry-cli-Linux-x86_64 46%
fetching sentry-cli-Linux-x86_64 47%
fetching sentry-cli-Linux-x86_64 48%
fetching sentry-cli-Linux-x86_64 49%
fetching sentry-cli-Linux-x86_64 50%
fetching sentry-cli-Linux-x86_64 51%
fetching sentry-cli-Linux-x86_64 52%
fetching sentry-cli-Linux-x86_64 53%
fetching sentry-cli-Linux-x86_64 54%
fetching sentry-cli-Linux-x86_64 55%
fetching sentry-cli-Linux-x86_64 56%
fetching sentry-cli-Linux-x86_64 57%
fetching sentry-cli-Linux-x86_64 58%
fetching sentry-cli-Linux-x86_64 59%
fetching sentry-cli-Linux-x86_64 60%
fetching sentry-cli-Linux-x86_64 61%
fetching sentry-cli-Linux-x86_64 62%
fetching sentry-cli-Linux-x86_64 63%
fetching sentry-cli-Linux-x86_64 64%
fetching sentry-cli-Linux-x86_64 65%
fetching sentry-cli-Linux-x86_64 66%
fetching sentry-cli-Linux-x86_64 67%
fetching sentry-cli-Linux-x86_64 68%
fetching sentry-cli-Linux-x86_64 69%
fetching sentry-cli-Linux-x86_64 70%
fetching sentry-cli-Linux-x86_64 71%
fetching sentry-cli-Linux-x86_64 72%
fetching sentry-cli-Linux-x86_64 73%
fetching sentry-cli-Linux-x86_64 74%
fetching sentry-cli-Linux-x86_64 75%
fetching sentry-cli-Linux-x86_64 76%
fetching sentry-cli-Linux-x86_64 77%
fetching sentry-cli-Linux-x86_64 78%
fetching sentry-cli-Linux-x86_64 79%
fetching sentry-cli-Linux-x86_64 80%
fetching sentry-cli-Linux-x86_64 81%
fetching sentry-cli-Linux-x86_64 82%
fetching sentry-cli-Linux-x86_64 83%
fetching sentry-cli-Linux-x86_64 84%
fetching sentry-cli-Linux-x86_64 85%
fetching sentry-cli-Linux-x86_64 86%
fetching sentry-cli-Linux-x86_64 87%
fetching sentry-cli-Linux-x86_64 88%
fetching sentry-cli-Linux-x86_64 89%
fetching sentry-cli-Linux-x86_64 90%
fetching sentry-cli-Linux-x86_64 91%
fetching sentry-cli-Linux-x86_64 92%
fetching sentry-cli-Linux-x86_64 93%
fetching sentry-cli-Linux-x86_64 94%
fetching sentry-cli-Linux-x86_64 95%
fetching sentry-cli-Linux-x86_64 96%
fetching sentry-cli-Linux-x86_64 97%
fetching sentry-cli-Linux-x86_64 98%
fetching sentry-cli-Linux-x86_64 99%
fetching sentry-cli-Linux-x86_64 100%
Error: Command failed: /usr/src/app/node_modules/@sentry/cli/sentry-cli --version
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 1: /usr/src/app/node_modules/@sentry/cli/sentry-cli: Âª: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 1: /usr/src/app/node_modules/@sentry/cli/sentry-cli: ELF: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 1: /usr/src/app/node_modules/@sentry/cli/sentry-cli: Â: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 2: /usr/src/app/node_modules/@sentry/cli/sentry-cli: 0Ê: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 3: /usr/src/app/node_modules/@sentry/cli/sentry-cli: ¨D
                                                                                                         : not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 1: /usr/src/app/node_modules/@sentry/cli/sentry-cli: Â: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 2: /usr/src/app/node_modules/@sentry/cli/sentry-cli: : not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 5: /usr/src/app/node_modules/@sentry/cli/sentry-cli: ÂªÂ: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 1: /usr/src/app/node_modules/@sentry/cli/sentry-cli: Âª: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 6: /usr/src/app/node_modules/@sentry/cli/sentry-cli: :¸: not found
/usr/src/app/node_modules/@sentry/cli/sentry-cli: 6: /usr/src/app/node_modules/@sentry/cli/sentry-cli: Syntax error: Unterminated quoted string

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-environment-jsdom-fourteen/node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-infinite-scroller@1.2.4 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-pdf@4.2.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-pdf@4.2.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/create-react-context@0.2.5 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/icons-react@2.0.1 requires a peer of react@16.x but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.2 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.2 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-lazy-load@3.1.13 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-lazy-load@3.1.13 requires a peer of react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.25.2 requires a peer of react@^0.14.0 || ^15.0.1 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.25.2 requires a peer of react-dom@^0.14.0 || ^15.0.1 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.1.266 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@2.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@8.3.0 requires a peer of eslint@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-umi@1.6.0 requires a peer of eslint-plugin-jsx-a11y@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-umi@1.6.0 requires a peer of eslint-plugin-react-hooks@1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@5.3.2 requires a peer of webpack@^5.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of typescript@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN esbuild-loader@2.9.2 requires a peer of webpack@^4.40.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @umijs/plugin-layout@0.17.2 requires a peer of @ant-design/icons@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @umijs/plugin-layout@0.17.2 requires a peer of @ant-design/pro-layout@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.2 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN dva@2.6.0-beta.22 requires a peer of react@^16.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN dva@2.6.0-beta.22 requires a peer of react-dom@^16.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN dva-immer@0.5.2 requires a peer of dva@^2.5.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-loading@3.0.22 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN connected-react-router@6.5.2 requires a peer of react@^16.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-intl@3.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint-plugin-flowtype@3.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint-plugin-jsx-a11y@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint-plugin-react-hooks@1.x but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.69.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.69.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-30T03_22_53_691Z-debug.log`

### Expected Result

fix package version & downgrade to 1.68.0 can fix this

**Comment by FeSeason** [comment] 2021-09-30 08:33
same error

**Comment by kamilogorek** [comment] 2021-09-30 10:00
Duplicate of https://github.com/getsentry/sentry-cli/issues/1035

**Closed by kamilogorek** 2021-09-30 10:00 UTC
