### ISSUE TITLE
Fails to upload dSYM file if there is a space in the path

### ISSUE THREAD

**Issue by soffes** [getsentry/sentry-cli#2] opened 2016-05-05 18:57 UTC
Even if you quote it in terminal, it will fail to upload.

**Comment by mitsuhiko** [comment] 2016-05-06 17:58
That's odd. I just uploaded one with spaces and it works for me. Where are you encountering spaces?

**Comment by mitsuhiko** [comment] 2016-05-28 16:13
Cannot reproduce. Closing :)

**Closed by mitsuhiko** 2016-05-28 16:13 UTC
