### ISSUE TITLE
ERROR in Sentry CLI Plugin: Command failed sentry-cli releases files...

### ISSUE THREAD

**Issue by MmtBkn** [getsentry/sentry-cli#192] opened 2017-12-20 18:11 UTC
Hello,

I'm using webpack plugin, and trying to upload release to sentry.

However, I'm getting following error from cli;
`ERROR in Sentry CLI Plugin: Command failed: node_modules/@sentry/cli/sentry-cli releases files 447ab upload-sourcemaps . --rewrite --ignore node_modules --ignore webpack.config.js`

And when I run code manually, 

```
> Rewriting sources
> Adding source map references
> Uploading source maps for release BUILD:25
> ~/app/xxxxxx/xxxxxxxx/xxxxxxxxx/xxxxxxxxxxxxxxxx.js
██████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 18/81
Segmentation fault: 11

```

It's uploading some files, and failing.

Versions:
```
"@sentry/cli": "^1.26.1",
"@sentry/webpack-plugin": "^1.1.0",
```
Thank you.

**Comment by jan-auer** [comment] 2017-12-21 08:37
Hi @MmtBkn, could you please add `--log-level=debug` as first parameter and then send us both the command invocation and the output? Also, it would be great, if you could please archive and send us the folder you are running sentry-cli from, so we can have a look at what's happening. Thank you!

**Comment by mitsuhiko** [comment] 2017-12-21 08:40
The only dep I can see that can segfault is the chardet one. Since the last item it processes is a javascript source file this would also be something that is being executed. So in theory this no longer happens on master where the dep is gone.

**Comment by jan-auer** [comment] 2017-12-21 08:45
Good point, completely forgot that we replaced that already. So you could try with one of the nightly builds:
- [sentry-cli-Darwin-x86_64](https://s3.amazonaws.com/getsentry-builds/getsentry/sentry-cli/adcf723e6860b8bfa7388ce20c8c08527e851243/sentry-cli-Darwin-x86_64)
- [sentry-cli-Linux-i686](https://s3.amazonaws.com/getsentry-builds/getsentry/sentry-cli/adcf723e6860b8bfa7388ce20c8c08527e851243/sentry-cli-Linux-i686)
- [sentry-cli-Linux-x86_64](https://s3.amazonaws.com/getsentry-builds/getsentry/sentry-cli/adcf723e6860b8bfa7388ce20c8c08527e851243/sentry-cli-Linux-x86_64)
- [sentry-cli-Windows-i686.exe](https://s3.amazonaws.com/getsentry-builds/getsentry/sentry-cli/adcf723e6860b8bfa7388ce20c8c08527e851243/sentry-cli-Windows-i686.exe)
- [sentry-cli-Windows-x86_64.exe](https://s3.amazonaws.com/getsentry-builds/getsentry/sentry-cli/adcf723e6860b8bfa7388ce20c8c08527e851243/sentry-cli-Windows-x86_64.exe)

**Comment by MmtBkn** [comment] 2017-12-22 00:06
Actually, I removed options from configuration and It works. 

```
const SentryCliPlugin = require('@sentry/webpack-plugin');

const config = {
  plugins: [
    new SentryCliPlugin({
      release: function(hash) {
        return hash.slice(0, 5);
      },
      include: '.',
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties'
    })
  ]
};
```

**Comment by jan-auer** [comment] 2018-01-02 16:15
Closing this as it seems fixed and we also likely removed the cause of this issue. Please feel free to reopen, if it happens again.

**Comment by jcrben** [comment] 2018-03-14 23:35
We ((@cyphernet and I) are getting this error and I are getting this error running 1.30.3 - sounds like it should be fixed by now?

Will email you the log hopefully before too long, want to double-check that there's nothing we don't want to reveal in there.

**Comment by andrewchae** [comment] 2018-04-04 22:54
I'm also having this issue but if I set log level to debug I get the maxBuffer issue from #206

**Comment by matthiasp42** [comment] 2018-07-26 21:39
I also have this issue. @jcrben @andrewchae did you figure it out?

**Comment by andrewchae** [comment] 2018-07-27 20:33
@matthiasp42 mine started working with an update

**Comment by macolo** [comment] 2018-09-09 21:11
Note: its better to do this via the sentry-cli in the deploy script.

**Comment by rudavko** [comment] 2018-09-20 14:37
Was having the same problem. The issue was an empty js file

**Comment by psychowico** [comment] 2018-09-27 13:16
Same problem here - empty JavaScript file broke uploading.

**Comment by mitsuhiko** [comment] 2019-05-24 11:49
Fixed in latest release. Turns out this was a bug in the curl binding for rust.

**Closed by mitsuhiko** 2019-05-24 11:49 UTC
Labels: bug
