### ISSUE TITLE
I install the cli, But the Xcode tip this message?

### ISSUE THREAD

**Issue by zhu-hongwei** [getsentry/sentry-cli#1977] opened 2024-03-12 09:20 UTC
### Environment

What version of the CLI and what OS are you running?
macOS 13.5
Xcode 15.2 (15C500b)

### Steps to Reproduce

What you did?
use the Sentry in my iOS app

### Expected Result

What you thought would happen?
Don't remind me to install it

### Actual Result

What actually happened?
Always remind me to install it

### Logs

When filing a bug report, please attach debug logs, either by using `--log-level=debug` flag or `SENTRY_LOG_LEVEL=debug` environment variable.
<img width="932" alt="image" src="https://github.com/getsentry/sentry-cli/assets/61079864/2511687e-293d-4979-aa03-47aabb20a91c">

**Comment by szokeasaurusrex** [comment] 2024-03-12 10:51
Hi @zhu-hongwei, how did you install Sentry CLI? Via Homebrew or via the install script?

If you installed via Homebrew, then this issue is likely a duplicate of #1320.

**Comment by zhu-hongwei** [comment] 2024-03-12 11:20
Via Homebrew

```
brew install sentry-cli
```

**Comment by szokeasaurusrex** [comment] 2024-03-12 11:26
@zhu-hongwei Looks like a duplicate of #1320, then.

You should be able to solve the problem by following the steps listed here: https://github.com/getsentry/sentry-cli/issues/1320#issuecomment-1243862732. If you are still struggling, please reopen the issue and explain where you got stuck.

**Closed by szokeasaurusrex** 2024-03-12 11:26 UTC
Labels: Waiting for: Product Owner
