### ISSUE TITLE
Cannot use -p option in sentry-cli releases

### ISSUE THREAD

**Issue by BramRoets** [getsentry/sentry-cli#1189] opened 2022-04-12 12:36 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-cli 2.0.0

### Steps to Reproduce

It looks like the `-p` option is broken. `---project` still works.

```
sentry-cli releases new -p my-project
```

### Expected Result

The same as running `sentry-cli releases new --project my-project` (Which used to work until version 2.0.0)

### Actual Result

`error: Found argument 'my-project' which wasn't expected, or isn't valid in this context`

**Comment by dpetrovaliev** [comment] 2022-04-12 12:49
I have the same issue since the 2.0.0 release.

**Comment by kamilogorek** [comment] 2022-04-12 13:14
Duplicate of https://github.com/getsentry/sentry-cli/issues/1186

2.0.1 release is in progress.

**Closed** 2022-04-12 13:14 UTC

**Comment by kamilogorek** [comment] 2022-04-12 14:08
`2.0.1` with fixed hyphenated names has been published.
