### ISSUE TITLE
Authentication error on creating deploy with correct authentication token.

### ISSUE THREAD

**Issue by hsleewis** [getsentry/sentry-cli#1939] opened 2024-02-12 14:05 UTC
### Environment

sentry-cli version: 2.28.5, platform: "linux", architecture: "x86_64"

### Steps to Reproduce
Creating a deploy fails with authentication error.

```sentry-cli" "releases" "deploys" "--release" "<.....>" "new" "-e" "production"```

### Expected Result
new deploy on sentry

### Actual Result
Authentication error.
Unrecognized auth token format!

response:
body: {"projects":["Insufficient access to project"]}

It's not an auth error because before I try to create the deploy I can successfully create a new release and upload the sourcemap with the same authentication token.

I think this started with todays release, last week there were no issues at all.

Anyone else have the same issue or knows how to solve it?

**Comment by VincentClair** [comment] 2024-02-12 14:34
Hello, I have the same error. It seems there is no sufficient rights with our actual tocken.
It works with 2.28.0 but fails for 2.28.4 and 2.28.5 (no tries for intermediary versions).

Changed "Project" permissions from "No Access" to "Read & Write" (have not try "Read" only).

**Comment by warmwaffles** [comment] 2024-02-12 15:45
I can confirm this for us as well. Was failing for `2.28.5`.

**Comment by szokeasaurusrex** [comment] 2024-02-12 16:01
@hsleewis, I tried to reproduce your error by running the same command you ran, using version `2.28.5`, but everything worked as expected for me.

If you downgrade to Sentry CLI `2.28.0`[^1] but keep everything else the same, do you still experience the same error?

If not, could you please rerun the command that causes the error on version `2.28.5` with `--log-level=debug`, and paste the full output logs of the command?

[^1]: Version `2.28.0` is the version immediately prior to `2.28.5`. Some intermediate versions may exist on some platforms, but because we were experiencing problems with our release process, none of these were fully released to all platforms.

**Comment by hsleewis** [comment] 2024-02-12 16:08
@szokeasaurusrex 
> If you downgrade to Sentry CLI `2.28.0`[1](#user-content-fn-1-facea5458b7fde8387b62034645aea9c) but keep everything else the same, do you still experience the same error?

No, everything works as expected on 2.28.0
 
> If not, could you please rerun the command that causes the error on version `2.28.5` with `--log-level=debug`, and paste the full output logs of the command?
I'll do that later tonight

**Comment by warmwaffles** [comment] 2024-02-12 16:09
Fairly certain this is the culprit https://github.com/getsentry/sentry-cli/commit/e11e231bb6b59fb3c5c5e6a235bbe93151bad129 it tries to read the projects when the official documentation says "no access" is the minimum.

**Comment by szokeasaurusrex** [comment] 2024-02-12 16:18
Yes, I was also thinking that this change might have something to do with https://github.com/getsentry/sentry-cli/commit/e11e231bb6b59fb3c5c5e6a235bbe93151bad129. Can you please link the official documentation that you are referring to @warmwaffles?

**Comment by warmwaffles** [comment] 2024-02-12 16:21
@szokeasaurusrex https://docs.sentry.io/product/accounts/auth-tokens/ "User Auth Tokens" section screenshot. Digging in to https://docs.sentry.io/product/integrations/integration-platform/ has a different screenshot of permissions necessary.

**Comment by szokeasaurusrex** [comment] 2024-02-12 16:30
@warmwaffles, from what I can tell, the screenshots you have mentioned are only examples that showcase possible configuration values; they are not specific to permissions necessary for creating release deploys in the Sentry CLI.

I still agree with you that e11e231 is the most likely culprit because it is the main change between 2.28.0 and 2.28.5; however, the pages you linked don't appear to provide any information about what the minimum permissions should be for creating a release deploy.

**Comment by JiriNedorost** [comment] 2024-02-12 16:43
For example in this part of docs it specifically mentions only Release & Organization permissions.
https://docs.sentry.io/product/releases/setup/release-automation/circleci/
Same for other integrations that are not one-step.

**Comment by szokeasaurusrex** [comment] 2024-02-12 16:44
Thank you @hsleewis! Would you also be able to provide the output of `sentry-cli info` (please call it with the same auth token as you used in the `releases deploy` command)?

One thing I would also recommend trying is for you to regenerate your auth token and try again because these two lines appear in your output:
```
package[4193375]: npx command failed: WARN    2024-02-12 16:16:08.372875807 +00:00 Unrecognized auth token format!
package[4193375]: Hint: Did you copy your token correctly?
```
The CLI performs a local validation of all auth tokens, and prints this warning if it detects that the auth token has an invalid format. There is probably some problem with your auth token (for example, you might have copy-pasted incorrectly), and this warning could possibly explain why you are facing difficulties (although, it is admittedly a bit strange that things broke from `2.28.0` to `2.28.5` if this is the case)

**Comment by warmwaffles** [comment] 2024-02-12 16:46
Also here @szokeasaurusrex https://blog.sentry.io/automating-sentry-releases-with-circleci/ this is what was used to setup our CircleCI originally in 2022.

**Comment by hsleewis** [comment] 2024-02-12 16:51
> Would you also be able to provide the output of sentry-cli info (

Yes, but I'll have to update the deploy script that I use to run the cli commands, will do it within a couple of hours.

> One thing I would also recommend trying is for you to regenerate your auth token and try again because these two lines appear in your output:

That's the whole issue, there is nothing wrong with the auth token, the same warning does not happen with any other CLI command, only when creating the deploy, not with creating the release and not with uploading the source maps.

> The CLI performs a local validation of all auth tokens, and prints this warning if it detects that the auth token has an invalid format. There is probably some problem with your auth token (for example, you might have copy-pasted incorrectly), and this warning could possibly explain why you are facing difficulties (although, it is admittedly a bit strange that things broke from 2.28.0 to 2.28.5 if this is the case)

Any idea why the warning doesn't show with any other command?

**Comment by szokeasaurusrex** [comment] 2024-02-12 17:05
@hsleewis 

> That's the whole issue, there is nothing wrong with the auth token, the same warning does not happen with any other CLI command, only when creating the deploy, not with creating the release and not with uploading the source maps.

That is really quite odd; the only place in our codebase that prints this warning message is the code that parses auth tokens, so the only reasonable explanation I can think of is that maybe you are somehow using a different auth token when running the `releases deploy` command versus any other command. But, I have no idea why that would be the case. 

How are you setting the auth token: in a `.sentryclirc` file (includes via `sentry-cli login`), via an environment variable, or via the `--auth-token` CLI argument?

> Any idea why the warning doesn't show with any other command? Any idea why the warning doesn't show with any other command?

Yes, this is indeed quite strange – I believe this warning should show with every CLI command (or at least the ones that require an auth token, like `sentry-cli sourcemaps upload`), as long as you are calling them with the same auth token.

**Comment by szokeasaurusrex** [comment] 2024-02-12 17:10
@JiriNedorost @warmwaffles, thank you for the information, I will look more into this. However, we are not querying the projects from the server at any point as a result of this change (the `config.get_projects` call in e11e231 is querying the local configuration only, in case this was confusing you)

**Comment by hsleewis** [comment] 2024-02-12 19:07
@szokeasaurusrex 
> Thank you @hsleewis! Would you also be able to provide the output of `sentry-cli info` (please call it with the same auth token as you used in the `releases deploy` command)?

is this you're looking for?
```
File: dir,	Node: Top,	This is the top of the INFO tree.

This is the Info main menu (aka directory node).
A few useful Info commands:

  'q' quits;
  'H' lists all Info commands;
  'h' starts the Info tutorial;
  'mTexinfo RET' visits the Texinfo manual, etc.

* Menu:

Basics
* Common options: (coreutils)Common options.
* Coreutils: (coreutils).       Core GNU (file, text, shell) utilities.
* Date input formats: (coreutils)Date input formats.
* Ed: (ed).                     The GNU line editor
* File permissions: (coreutils)File permissions.
                                Access modes.
* Finding files: (find).        Operating on files matching certain criteria.

Compression
* Gzip: (gzip).                 General (de)compression of files (lzw).

Editors
* nano: (nano).                 Small and friendly text editor.

General Commands
* Screen: (screen).             Full-screen window manager.

GNU organization
* Maintaining Findutils: (find-maint).
                                Maintaining GNU findutils

GNU Utilities
* dirmngr-client: (gnupg).      X.509 CRL and OCSP client.
* dirmngr: (gnupg).             X.509 CRL and OCSP server.
* gpg-agent: (gnupg).           The secret key daemon.
* gpg2: (gnupg).                OpenPGP encryption and signing tool.
* gpgsm: (gnupg).               S/MIME encryption and signing tool.

Individual utilities
* arch: (coreutils)arch invocation.             Print machine hardware name.
* b2sum: (coreutils)b2sum invocation.           Print or check BLAKE2 digests.
* base32: (coreutils)base32 invocation.         Base32 encode/decode data.
* base64: (coreutils)base64 invocation.         Base64 encode/decode data.
* basename: (coreutils)basename invocation.     Strip directory and suffix.
* cat: (coreutils)cat invocation.               Concatenate and write files.
* chcon: (coreutils)chcon invocation.           Change SELinux CTX of files.
* chgrp: (coreutils)chgrp invocation.           Change file groups.
* chmod: (coreutils)chmod invocation.           Change access permissions.
* chown: (coreutils)chown invocation.           Change file owners and groups.
* chroot: (coreutils)chroot invocation.         Specify the root directory.
* cksum: (coreutils)cksum invocation.           Print POSIX CRC checksum.
* cmp: (diffutils)Invoking cmp.                 Compare 2 files byte by byte.
* comm: (coreutils)comm invocation.             Compare sorted files by line.
* cp: (coreutils)cp invocation.                 Copy files.
* csplit: (coreutils)csplit invocation.         Split by context.
* cut: (coreutils)cut invocation.               Print selected parts of lines.
* date: (coreutils)date invocation.             Print/set system date and time.
* dd: (coreutils)dd invocation.                 Copy and convert a file.
* df: (coreutils)df invocation.                 Report file system disk usage.
* diff: (diffutils)Invoking diff.               Compare 2 files line by line.
* diff3: (diffutils)Invoking diff3.             Compare 3 files line by line.
* dir: (coreutils)dir invocation.               List directories briefly.
* dircolors: (coreutils)dircolors invocation.   Color setup for ls.
* dirname: (coreutils)dirname invocation.       Strip last file name component.
* du: (coreutils)du invocation.                 Report on disk usage.
* echo: (coreutils)echo invocation.             Print a line of text.
* env: (coreutils)env invocation.               Modify the environment.
* expand: (coreutils)expand invocation.         Convert tabs to spaces.
* expr: (coreutils)expr invocation.             Evaluate expressions.
* factor: (coreutils)factor invocation.         Print prime factors
* false: (coreutils)false invocation.           Do nothing, unsuccessfully.
* find: (find)Invoking find.                    Finding and acting on files.
* fmt: (coreutils)fmt invocation.               Reformat paragraph text.
* fold: (coreutils)fold invocation.             Wrap long input lines.
* groups: (coreutils)groups invocation.         Print group names a user is in.
* gunzip: (gzip)Overview.                       Decompression.
* gzexe: (gzip)Overview.                        Compress executables.
* head: (coreutils)head invocation.             Output the first part of files.
* hostid: (coreutils)hostid invocation.         Print numeric host identifier.
* hostname: (coreutils)hostname invocation.     Print or set system name.
* id: (coreutils)id invocation.                 Print user identity.
* install: (coreutils)install invocation.       Copy files and set attributes.
* join: (coreutils)join invocation.             Join lines on a common field.
* kill: (coreutils)kill invocation.             Send a signal to processes.
* link: (coreutils)link invocation.             Make hard links between files.
* ln: (coreutils)ln invocation.                 Make links between files.
* locate: (find)Invoking locate.                Finding files in a database.
* logname: (coreutils)logname invocation.       Print current login name.
* ls: (coreutils)ls invocation.                 List directory contents.
* md5sum: (coreutils)md5sum invocation.         Print or check MD5 digests.
* mkdir: (coreutils)mkdir invocation.           Create directories.
* mkfifo: (coreutils)mkfifo invocation.         Create FIFOs (named pipes).
* mknod: (coreutils)mknod invocation.           Create special files.
* mktemp: (coreutils)mktemp invocation.         Create temporary files.
* mv: (coreutils)mv invocation.                 Rename files.
* nice: (coreutils)nice invocation.             Modify niceness.
* nl: (coreutils)nl invocation.                 Number lines and write files.
* nohup: (coreutils)nohup invocation.           Immunize to hangups.
* nproc: (coreutils)nproc invocation.           Print the number of processors.
* numfmt: (coreutils)numfmt invocation.         Reformat numbers.
* od: (coreutils)od invocation.                 Dump files in octal, etc.
* paste: (coreutils)paste invocation.           Merge lines of files.
* patch: (diffutils)Invoking patch.             Apply a patch to a file.
* pathchk: (coreutils)pathchk invocation.       Check file name portability.
* pr: (coreutils)pr invocation.                 Paginate or columnate files.
* printenv: (coreutils)printenv invocation.     Print environment variables.
* printf: (coreutils)printf invocation.         Format and print data.
* ptx: (coreutils)ptx invocation.               Produce permuted indexes.
* pwd: (coreutils)pwd invocation.               Print working directory.
* readlink: (coreutils)readlink invocation.     Print referent of a symlink.
* realpath: (coreutils)realpath invocation.     Print resolved file names.
* rm: (coreutils)rm invocation.                 Remove files.
* rmdir: (coreutils)rmdir invocation.           Remove empty directories.
* runcon: (coreutils)runcon invocation.         Run in specified SELinux CTX.
* sdiff: (diffutils)Invoking sdiff.             Merge 2 files side-by-side.
* seq: (coreutils)seq invocation.               Print numeric sequences
* sha1sum: (coreutils)sha1sum invocation.       Print or check SHA-1 digests.
* sha2: (coreutils)sha2 utilities.              Print or check SHA-2 digests.
* shred: (coreutils)shred invocation.           Remove files more securely.
* shuf: (coreutils)shuf invocation.             Shuffling text files.
* sleep: (coreutils)sleep invocation.           Delay for a specified time.
* sort: (coreutils)sort invocation.             Sort text files.
* split: (coreutils)split invocation.           Split into pieces.
* stat: (coreutils)stat invocation.             Report file(system) status.
* stdbuf: (coreutils)stdbuf invocation.         Modify stdio buffering.
* stty: (coreutils)stty invocation.             Print/change terminal settings.
* sum: (coreutils)sum invocation.               Print traditional checksum.
* sync: (coreutils)sync invocation.             Synchronize memory to disk.
* tac: (coreutils)tac invocation.               Reverse files.
* tail: (coreutils)tail invocation.             Output the last part of files.
* tee: (coreutils)tee invocation.               Redirect to multiple files.
* test: (coreutils)test invocation.             File/string tests.
* time: (time).                                 Run programs and summarize
                                                  system resource usage.
* timeout: (coreutils)timeout invocation.       Run with time limit.
* touch: (coreutils)touch invocation.           Change file timestamps.
* tr: (coreutils)tr invocation.                 Translate characters.
* true: (coreutils)true invocation.             Do nothing, successfully.
* truncate: (coreutils)truncate invocation.     Shrink/extend size of a file.
* tsort: (coreutils)tsort invocation.           Topological sort.
* tty: (coreutils)tty invocation.               Print terminal name.
* uname: (coreutils)uname invocation.           Print system information.
* unexpand: (coreutils)unexpand invocation.     Convert spaces to tabs.
* uniq: (coreutils)uniq invocation.             Uniquify files.
* unlink: (coreutils)unlink invocation.         Removal via unlink(2).
* updatedb: (find)Invoking updatedb.            Building the locate database.
* uptime: (coreutils)uptime invocation.         Print uptime and load.
* users: (coreutils)users invocation.           Print current user names.
* vdir: (coreutils)vdir invocation.             List directories verbosely.
* wc: (coreutils)wc invocation.                 Line, word, and byte counts.
* who: (coreutils)who invocation.               Print who is logged in.
* whoami: (coreutils)whoami invocation.         Print effective user ID.
* xargs: (find)Invoking xargs.                  Operating on many files.
* yes: (coreutils)yes invocation.               Print a string indefinitely.
* zcat: (gzip)Overview.                         Decompression to stdout.
* zdiff: (gzip)Overview.                        Compare compressed files.
* zforce: (gzip)Overview.                       Force .gz extension on files.
* zgrep: (gzip)Overview.                        Search compressed files.
* zmore: (gzip)Overview.                        Decompression output by pages.

Kernel
* GRUB: (grub).                 The GRand Unified Bootloader
* grub-dev: (grub-dev).         The GRand Unified Bootloader Dev
* grub-install: (grub)Invoking grub-install.
                                Install GRUB on your drive
* grub-mkconfig: (grub)Invoking grub-mkconfig.
                                Generate GRUB configuration
* grub-mkpasswd-pbkdf2: (grub)Invoking grub-mkpasswd-pbkdf2.
* grub-mkrelpath: (grub)Invoking grub-mkrelpath.
* grub-mkrescue: (grub)Invoking grub-mkrescue.
                                Make a GRUB rescue image
* grub-mount: (grub)Invoking grub-mount.
                                Mount a file system using GRUB
* grub-probe: (grub)Invoking grub-probe.
                                Probe device information
* grub-script-check: (grub)Invoking grub-script-check.

Libraries
* RLuserman: (rluserman).       The GNU readline library User's Manual.

Math
* bc: (bc).                     An arbitrary precision calculator language.

Network applications
* Wget: (wget).                 Non-interactive network downloader.

Texinfo documentation system
* info stand-alone: (info-stnd).
                                Read Info documents without Emacs.

Text creation and manipulation
* Diffutils: (diffutils).       Comparing and merging files.
* grep: (grep).                 Print lines that match patterns.
* sed: (sed).                   Stream EDitor.

Typesetting
* Groff: (groff).               The GNU troff document formatting system.
* ```

> How are you setting the auth token: in a `.sentryclirc` file (includes via `sentry-cli login`), via an environment variable, or via the `--auth-token` CLI argument?

Environment variable

**Comment by janpapenbrock** [comment] 2024-02-13 07:33
This is now blocking our deployment pipelines, too. Should we set the version to 2.28.0 manually on our side or will there be a rollback soon so we can stay on latest?

**Comment by GuillaumeCisco** [comment] 2024-02-13 09:09
Regenerating the global organization AUTH_TOKEN fixed the issue for us.

**Comment by mberrezak** [comment] 2024-02-13 09:39
Yes I did the same. A new token fixed the issue for us.

> Regenerating the global organization AUTH_TOKEN fixed the issue for us.

**Comment by szokeasaurusrex** [comment] 2024-02-13 10:07
>is this you're looking for?

@hsleewis, No, it is not. Could you please run the command `sentry-cli info` (using `sentry-cli` version `2.28.5`) and provide the output generated?

> This is now blocking our deployment pipelines, too. Should we set the version to 2.28.0 manually on our side or will there be a rollback soon so we can stay on latest?
@janpapenbrock (and everyone else who has been experiencing problems), we have just released `2.28.6` which rolls back the changes (e11e231) that likely caused this problem until we can determine how to resolve the problem more permanently. This will only be a temporary solution, however, since e11e231 contained changes which fixed a different bug (#1927), so I will eventually need to reapply the changes in a way that does not break things.

**Comment by szokeasaurusrex** [comment] 2024-02-13 10:08
Would anyone here be able to confirm whether `2.28.6` fixes the problems you were experiencing with `2.28.5`?

**Comment by szokeasaurusrex** [comment] 2024-02-13 11:13
> The supplied SENTRY_AUTH_TOKEN is a Custom Integration token on Organization level with scopes: org:read, project:releases. (It reads Project: No access in the scope settings table above)

Thank you @janpapenbrock for providing this information – it is exactly what I needed to be able to reproduce the issue on version `2.28.5`. I now should have all the information I need to be able to implement and test a permanent solution to this problem, so I will close this issue in favor of #1927

**Closed by szokeasaurusrex** 2024-02-13 11:14 UTC
Labels: Waiting for: Community

**Comment by warmwaffles** [comment] 2024-02-13 14:24
@szokeasaurusrex thank you for working through this.

**Comment by c0m1c5an5** [comment] 2025-05-07 11:11
There appears to be a regression of this issue.
The same problem occurs when using `2.43.0` as opposed to `2.28.6`.
The regression happened in `2.36.2`
