### ISSUE TITLE
SourceMaps explain says deprecated, not accurate but docs say to use it

### ISSUE THREAD

**Issue by broksonic21** [getsentry/sentry-cli#2070] opened 2024-05-23 14:20 UTC
### CLI Version

sentry-cli 2.31.2

### Operating System and Architecture

- [X] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.5

### CLI Command

npx sentry-cli sourcemaps explain REDACTED

### Exact Reproduction Steps

Run `npx sentry-cli sourcemaps explain REDACTED`

Get this deprecation warning:

```
⚠ DEPRECATION: `sourcemaps explain` has drifted from how sourcemap processing actually operates and its output may not be accurate. It will be removed in a future version of `sentry-cli`.
```

But https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#use-the-cli says to use it. Is there an alternative that does work? or can we make the cli match the docs or vice versa?

### Expected Results

`sourcemaps explain` works as per the docs

### Actual Results

```
⚠ DEPRECATION: `sourcemaps explain` has drifted from how sourcemap processing actually operates and its output may not be accurate. It will be removed in a future version of `sentry-cli`.
```

### Logs

n/a

**Comment by szokeasaurusrex** [comment] 2024-05-28 13:39
@broksonic21, the CLI output is correct; `sourcemaps explain` is in fact deprecated. We already have an [issue in our docs repository](https://github.com/getsentry/sentry-docs/issues/9638) to document the new method of debugging sourcemaps (directly in the Sentry UI) and to [remove the `sourcemaps explain` docs](https://github.com/getsentry/sentry-docs/issues/9638#issuecomment-2045136310).

I am closing this issue as a duplicate of the existing issue (https://github.com/getsentry/sentry-docs/issues/9638).

**Closed by szokeasaurusrex** 2024-05-28 13:39 UTC
Labels: Waiting for: Product Owner
